// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

class TwoFourSevenOfficeAuthTokens {
  String token;

  TwoFourSevenOfficeAuthTokens({
    required this.token
  });

  factory TwoFourSevenOfficeAuthTokens.fromMap(Map<String, dynamic> map) {
    return TwoFourSevenOfficeAuthTokens(
  token: map['token'].toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'token': token
    };
  }
}
