// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

enum Locale {
  norwegian,
  english
}

class AppNotices {
  String title;
  String description;
  int priority;
  bool isActive;
  Locale locale;
  String? color;
  String? actionUrl;
  String? actionLabel;

  AppNotices({
    required this.title,
    required this.description,
    required this.priority,
    required this.isActive,
    required this.locale,
    this.color,
    this.actionUrl,
    this.actionLabel
  });

  factory AppNotices.fromMap(Map<String, dynamic> map) {
    return AppNotices(
  title: map['title'].toString(),
  description: map['description'].toString(),
  priority: map['priority'],
  isActive: map['isActive'],
  locale: Locale.values.firstWhere((e) => e.name == map['locale']),
  color: map['color']?.toString(),
  actionUrl: map['actionUrl']?.toString(),
  actionLabel: map['actionLabel']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'title': title,
  'description': description,
  'priority': priority,
  'isActive': isActive,
  'locale': locale.name,
  'color': color,
  'actionUrl': actionUrl,
  'actionLabel': actionLabel
    };
  }
}
