// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

class AuditLogs {
  String action;
  String? actorId;
  String? actorEmail;
  String? resourceId;
  String? resourceType;
  String? payload;

  AuditLogs({
    required this.action,
    this.actorId,
    this.actorEmail,
    this.resourceId,
    this.resourceType,
    this.payload
  });

  factory AuditLogs.fromMap(Map<String, dynamic> map) {
    return AuditLogs(
  action: map['action'].toString(),
  actorId: map['actor_id']?.toString(),
  actorEmail: map['actor_email']?.toString(),
  resourceId: map['resource_id']?.toString(),
  resourceType: map['resource_type']?.toString(),
  payload: map['payload']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'action': action,
  'actor_id': actorId,
  'actor_email': actorEmail,
  'resource_id': resourceId,
  'resource_type': resourceType,
  'payload': payload
    };
  }
}
