// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

class BenefitReveals {
  String userId;
  String benefitId;
  String revealedAt;

  BenefitReveals({
    required this.userId,
    required this.benefitId,
    required this.revealedAt
  });

  factory BenefitReveals.fromMap(Map<String, dynamic> map) {
    return BenefitReveals(
  userId: map['user_id'].toString(),
  benefitId: map['benefit_id'].toString(),
  revealedAt: map['revealed_at'].toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'user_id': userId,
  'benefit_id': benefitId,
  'revealed_at': revealedAt
    };
  }
}
