// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'users.dart';

class BugReports {
  String userId;
  String? description;
  Users? user;
  List<String>? images;

  BugReports({
    required this.userId,
    this.description,
    this.user,
    this.images
  });

  factory BugReports.fromMap(Map<String, dynamic> map) {
    return BugReports(
  userId: map['user_id'].toString(),
  description: map['description']?.toString(),
  user: map['user'] != null ? Users.fromMap(map['user']) : null,
  images: List<String>.from(map['images'] ?? [])
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'user_id': userId,
  'description': description,
  'user': user?.toMap(),
  'images': images
    };
  }
}
