// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'department_board.dart';

class CampusData {
  String? description;
  List<String>? businessBenefits;
  List<String>? studentBenefits;
  List<String>? careerAdvantages;
  List<String>? socialNetwork;
  List<String>? safety;
  String? location;
  List<DepartmentBoard>? departmentBoard;
  String? name;
  String? nameEn;
  String? nameNb;
  String? descriptionEn;
  String? taglineNb;
  String? taglineEn;
  List<String>? highlightsNb;
  List<String>? highlightsEn;
  List<String>? focusAreasNb;
  List<String>? focusAreasEn;
  String? servicesNb;
  List<String>? studentBenefitsNb;
  List<String>? studentBenefitsEn;
  List<String>? careerAdvantagesNb;
  List<String>? careerAdvantagesEn;
  List<String>? socialNetworkNb;
  List<String>? socialNetworkEn;
  List<String>? safetyNb;
  List<String>? safetyEn;
  List<String>? businessBenefitsNb;
  List<String>? businessBenefitsEn;
  String? descriptionNb;

  CampusData({
    this.description,
    this.businessBenefits,
    this.studentBenefits,
    this.careerAdvantages,
    this.socialNetwork,
    this.safety,
    this.location,
    this.departmentBoard,
    this.name,
    this.nameEn,
    this.nameNb,
    this.descriptionEn,
    this.taglineNb,
    this.taglineEn,
    this.highlightsNb,
    this.highlightsEn,
    this.focusAreasNb,
    this.focusAreasEn,
    this.servicesNb,
    this.studentBenefitsNb,
    this.studentBenefitsEn,
    this.careerAdvantagesNb,
    this.careerAdvantagesEn,
    this.socialNetworkNb,
    this.socialNetworkEn,
    this.safetyNb,
    this.safetyEn,
    this.businessBenefitsNb,
    this.businessBenefitsEn,
    this.descriptionNb
  });

  factory CampusData.fromMap(Map<String, dynamic> map) {
    return CampusData(
  description: map['description']?.toString(),
  businessBenefits: List<String>.from(map['businessBenefits'] ?? []),
  studentBenefits: List<String>.from(map['studentBenefits'] ?? []),
  careerAdvantages: List<String>.from(map['careerAdvantages'] ?? []),
  socialNetwork: List<String>.from(map['socialNetwork'] ?? []),
  safety: List<String>.from(map['safety'] ?? []),
  location: map['location']?.toString(),
  departmentBoard: (map['departmentBoard'] as List<dynamic>?)?.map((e) => DepartmentBoard.fromMap(e)).toList()
,
  name: map['name']?.toString(),
  nameEn: map['name_en']?.toString(),
  nameNb: map['name_nb']?.toString(),
  descriptionEn: map['description_en']?.toString(),
  taglineNb: map['tagline_nb']?.toString(),
  taglineEn: map['tagline_en']?.toString(),
  highlightsNb: List<String>.from(map['highlights_nb'] ?? []),
  highlightsEn: List<String>.from(map['highlights_en'] ?? []),
  focusAreasNb: List<String>.from(map['focusAreas_nb'] ?? []),
  focusAreasEn: List<String>.from(map['focusAreas_en'] ?? []),
  servicesNb: map['services_nb']?.toString(),
  studentBenefitsNb: List<String>.from(map['studentBenefits_nb'] ?? []),
  studentBenefitsEn: List<String>.from(map['studentBenefits_en'] ?? []),
  careerAdvantagesNb: List<String>.from(map['careerAdvantages_nb'] ?? []),
  careerAdvantagesEn: List<String>.from(map['careerAdvantages_en'] ?? []),
  socialNetworkNb: List<String>.from(map['socialNetwork_nb'] ?? []),
  socialNetworkEn: List<String>.from(map['socialNetwork_en'] ?? []),
  safetyNb: List<String>.from(map['safety_nb'] ?? []),
  safetyEn: List<String>.from(map['safety_en'] ?? []),
  businessBenefitsNb: List<String>.from(map['businessBenefits_nb'] ?? []),
  businessBenefitsEn: List<String>.from(map['businessBenefits_en'] ?? []),
  descriptionNb: map['description_nb']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'description': description,
  'businessBenefits': businessBenefits,
  'studentBenefits': studentBenefits,
  'careerAdvantages': careerAdvantages,
  'socialNetwork': socialNetwork,
  'safety': safety,
  'location': location,
  'departmentBoard': departmentBoard?.map((e) => e.toMap()).toList()
,
  'name': name,
  'name_en': nameEn,
  'name_nb': nameNb,
  'description_en': descriptionEn,
  'tagline_nb': taglineNb,
  'tagline_en': taglineEn,
  'highlights_nb': highlightsNb,
  'highlights_en': highlightsEn,
  'focusAreas_nb': focusAreasNb,
  'focusAreas_en': focusAreasEn,
  'services_nb': servicesNb,
  'studentBenefits_nb': studentBenefitsNb,
  'studentBenefits_en': studentBenefitsEn,
  'careerAdvantages_nb': careerAdvantagesNb,
  'careerAdvantages_en': careerAdvantagesEn,
  'socialNetwork_nb': socialNetworkNb,
  'socialNetwork_en': socialNetworkEn,
  'safety_nb': safetyNb,
  'safety_en': safetyEn,
  'businessBenefits_nb': businessBenefitsNb,
  'businessBenefits_en': businessBenefitsEn,
  'description_nb': descriptionNb
    };
  }
}
