// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'departments.dart';
import 'users.dart';
import 'saved_jobs.dart';
import 'campus_data.dart';
import 'jobs.dart';
import 'events.dart';
import 'news.dart';
import 'webshop_products.dart';
import 'partners.dart';
import 'pages.dart';
import 'expenses.dart';

class Campus {
  String name;
  List<Departments>? departments;
  List<Users>? users;
  List<SavedJobs>? savedJobs;
  CampusData? campusData;
  List<Jobs>? jobs;
  List<Events>? events;
  List<News>? news;
  List<WebshopProducts>? webshopProducts;
  List<Partners>? partners;
  List<Pages>? pages;
  List<Expenses>? expenses;

  Campus({
    required this.name,
    this.departments,
    this.users,
    this.savedJobs,
    this.campusData,
    this.jobs,
    this.events,
    this.news,
    this.webshopProducts,
    this.partners,
    this.pages,
    this.expenses
  });

  factory Campus.fromMap(Map<String, dynamic> map) {
    return Campus(
  name: map['name'].toString(),
  departments: (map['departments'] as List<dynamic>?)?.map((e) => Departments.fromMap(e)).toList()
,
  users: (map['users'] as List<dynamic>?)?.map((e) => Users.fromMap(e)).toList()
,
  savedJobs: (map['savedJobs'] as List<dynamic>?)?.map((e) => SavedJobs.fromMap(e)).toList()
,
  campusData: map['campusData'] != null ? CampusData.fromMap(map['campusData']) : null,
  jobs: (map['jobs'] as List<dynamic>?)?.map((e) => Jobs.fromMap(e)).toList()
,
  events: (map['events'] as List<dynamic>?)?.map((e) => Events.fromMap(e)).toList()
,
  news: (map['news'] as List<dynamic>?)?.map((e) => News.fromMap(e)).toList()
,
  webshopProducts: (map['webshop_products'] as List<dynamic>?)?.map((e) => WebshopProducts.fromMap(e)).toList()
,
  partners: (map['partners'] as List<dynamic>?)?.map((e) => Partners.fromMap(e)).toList()
,
  pages: (map['pages'] as List<dynamic>?)?.map((e) => Pages.fromMap(e)).toList()
,
  expenses: (map['expenses'] as List<dynamic>?)?.map((e) => Expenses.fromMap(e)).toList()

    );
  }

  Map<String, dynamic> toMap() {
    return {
  'name': name,
  'departments': departments?.map((e) => e.toMap()).toList()
,
  'users': users?.map((e) => e.toMap()).toList()
,
  'savedJobs': savedJobs?.map((e) => e.toMap()).toList()
,
  'campusData': campusData?.toMap(),
  'jobs': jobs?.map((e) => e.toMap()).toList()
,
  'events': events?.map((e) => e.toMap()).toList()
,
  'news': news?.map((e) => e.toMap()).toList()
,
  'webshop_products': webshopProducts?.map((e) => e.toMap()).toList()
,
  'partners': partners?.map((e) => e.toMap()).toList()
,
  'pages': pages?.map((e) => e.toMap()).toList()
,
  'expenses': expenses?.map((e) => e.toMap()).toList()

    };
  }
}
