// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

class CampusMetadata {
  String campusId;
  String campusName;
  String? taglineNb;
  String? taglineEn;
  String? descriptionNb;
  String? descriptionEn;
  List<String>? highlightsNb;
  List<String>? highlightsEn;
  List<String>? focusAreasNb;
  List<String>? focusAreasEn;
  String? servicesNb;
  String? servicesEn;

  CampusMetadata({
    required this.campusId,
    required this.campusName,
    this.taglineNb,
    this.taglineEn,
    this.descriptionNb,
    this.descriptionEn,
    this.highlightsNb,
    this.highlightsEn,
    this.focusAreasNb,
    this.focusAreasEn,
    this.servicesNb,
    this.servicesEn
  });

  factory CampusMetadata.fromMap(Map<String, dynamic> map) {
    return CampusMetadata(
  campusId: map['campus_id'].toString(),
  campusName: map['campus_name'].toString(),
  taglineNb: map['tagline_nb']?.toString(),
  taglineEn: map['tagline_en']?.toString(),
  descriptionNb: map['description_nb']?.toString(),
  descriptionEn: map['description_en']?.toString(),
  highlightsNb: List<String>.from(map['highlights_nb'] ?? []),
  highlightsEn: List<String>.from(map['highlights_en'] ?? []),
  focusAreasNb: List<String>.from(map['focusAreas_nb'] ?? []),
  focusAreasEn: List<String>.from(map['focusAreas_en'] ?? []),
  servicesNb: map['services_nb']?.toString(),
  servicesEn: map['services_en']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'campus_id': campusId,
  'campus_name': campusName,
  'tagline_nb': taglineNb,
  'tagline_en': taglineEn,
  'description_nb': descriptionNb,
  'description_en': descriptionEn,
  'highlights_nb': highlightsNb,
  'highlights_en': highlightsEn,
  'focusAreas_nb': focusAreasNb,
  'focusAreas_en': focusAreasEn,
  'services_nb': servicesNb,
  'services_en': servicesEn
    };
  }
}
