// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

class CartReservations {
  String productId;
  String userId;
  int quantity;
  String expiresAt;

  CartReservations({
    required this.productId,
    required this.userId,
    required this.quantity,
    required this.expiresAt
  });

  factory CartReservations.fromMap(Map<String, dynamic> map) {
    return CartReservations(
  productId: map['product_id'].toString(),
  userId: map['user_id'].toString(),
  quantity: map['quantity'],
  expiresAt: map['expires_at'].toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'product_id': productId,
  'user_id': userId,
  'quantity': quantity,
  'expires_at': expiresAt
    };
  }
}
