// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

enum Type {
  text,
  image,
  file,
  system,
  product
}

class ChatMessages {
  String chatId;
  String senderId;
  String senderName;
  String content;
  Type type;
  List<String>? attachments;
  bool? isEdited;
  bool? isDeleted;
  String? replyToId;

  ChatMessages({
    required this.chatId,
    required this.senderId,
    required this.senderName,
    required this.content,
    required this.type,
    this.attachments,
    this.isEdited,
    this.isDeleted,
    this.replyToId
  });

  factory ChatMessages.fromMap(Map<String, dynamic> map) {
    return ChatMessages(
  chatId: map['chat_id'].toString(),
  senderId: map['sender_id'].toString(),
  senderName: map['sender_name'].toString(),
  content: map['content'].toString(),
  type: Type.values.firstWhere((e) => e.name == map['type']),
  attachments: List<String>.from(map['attachments'] ?? []),
  isEdited: map['is_edited'],
  isDeleted: map['is_deleted'],
  replyToId: map['reply_to_id']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'chat_id': chatId,
  'sender_id': senderId,
  'sender_name': senderName,
  'content': content,
  'type': type.name,
  'attachments': attachments,
  'is_edited': isEdited,
  'is_deleted': isDeleted,
  'reply_to_id': replyToId
    };
  }
}
