// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

enum Type {
  direct,
  group,
  team,
  department
}

class Chats {
  String name;
  Type type;
  List<String> participants;
  String? description;
  String? teamId;
  String? departmentId;
  bool? isActive;
  bool? isMuted;
  int? unreadCount;
  String? lastActivityAt;

  Chats({
    required this.name,
    required this.type,
    required this.participants,
    this.description,
    this.teamId,
    this.departmentId,
    this.isActive,
    this.isMuted,
    this.unreadCount,
    this.lastActivityAt
  });

  factory Chats.fromMap(Map<String, dynamic> map) {
    return Chats(
  name: map['name'].toString(),
  type: Type.values.firstWhere((e) => e.name == map['type']),
  participants: List<String>.from(map['participants'] ?? []),
  description: map['description']?.toString(),
  teamId: map['team_id']?.toString(),
  departmentId: map['department_id']?.toString(),
  isActive: map['is_active'],
  isMuted: map['is_muted'],
  unreadCount: map['unread_count'],
  lastActivityAt: map['last_activity_at']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'name': name,
  'type': type.name,
  'participants': participants,
  'description': description,
  'team_id': teamId,
  'department_id': departmentId,
  'is_active': isActive,
  'is_muted': isMuted,
  'unread_count': unreadCount,
  'last_activity_at': lastActivityAt
    };
  }
}
