// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'jobs.dart';
import 'events.dart';
import 'news.dart';
import 'webshop_products.dart';
import 'departments.dart';
import 'member_benefit.dart';

enum Locale {
  en,
  no
}

enum ContentType {
  job,
  event,
  news,
  product,
  department,
  memberBenefit,
  page
}

class ContentTranslations {
  String contentId;
  Locale locale;
  String title;
  String description;
  ContentType contentType;
  String? additionalFields;
  Jobs? jobRef;
  Events? eventRef;
  News? newsRef;
  WebshopProducts? productRef;
  String? shortDescription;
  Departments? departmentRef;
  MemberBenefit? memberBenefit;

  ContentTranslations({
    required this.contentId,
    required this.locale,
    required this.title,
    required this.description,
    required this.contentType,
    this.additionalFields,
    this.jobRef,
    this.eventRef,
    this.newsRef,
    this.productRef,
    this.shortDescription,
    this.departmentRef,
    this.memberBenefit
  });

  factory ContentTranslations.fromMap(Map<String, dynamic> map) {
    return ContentTranslations(
  contentId: map['content_id'].toString(),
  locale: Locale.values.firstWhere((e) => e.name == map['locale']),
  title: map['title'].toString(),
  description: map['description'].toString(),
  contentType: ContentType.values.firstWhere((e) => e.name == map['content_type']),
  additionalFields: map['additional_fields']?.toString(),
  jobRef: map['job_ref'] != null ? Jobs.fromMap(map['job_ref']) : null,
  eventRef: map['event_ref'] != null ? Events.fromMap(map['event_ref']) : null,
  newsRef: map['news_ref'] != null ? News.fromMap(map['news_ref']) : null,
  productRef: map['product_ref'] != null ? WebshopProducts.fromMap(map['product_ref']) : null,
  shortDescription: map['short_description']?.toString(),
  departmentRef: map['department_ref'] != null ? Departments.fromMap(map['department_ref']) : null,
  memberBenefit: map['memberBenefit'] != null ? MemberBenefit.fromMap(map['memberBenefit']) : null
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'content_id': contentId,
  'locale': locale.name,
  'title': title,
  'description': description,
  'content_type': contentType.name,
  'additional_fields': additionalFields,
  'job_ref': jobRef?.toMap(),
  'event_ref': eventRef?.toMap(),
  'news_ref': newsRef?.toMap(),
  'product_ref': productRef?.toMap(),
  'short_description': shortDescription,
  'department_ref': departmentRef?.toMap(),
  'memberBenefit': memberBenefit?.toMap()
    };
  }
}
