// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

class DashboardMetrics {
  String metricType;
  String metricData;
  String dateRange;
  String computedAt;

  DashboardMetrics({
    required this.metricType,
    required this.metricData,
    required this.dateRange,
    required this.computedAt
  });

  factory DashboardMetrics.fromMap(Map<String, dynamic> map) {
    return DashboardMetrics(
  metricType: map['metric_type'].toString(),
  metricData: map['metric_data'].toString(),
  dateRange: map['date_range'].toString(),
  computedAt: map['computed_at'].toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'metric_type': metricType,
  'metric_data': metricData,
  'date_range': dateRange,
  'computed_at': computedAt
    };
  }
}
