// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'campus.dart';
import 'users.dart';
import 'department_socials.dart';
import 'news.dart';
import 'jobs.dart';
import 'department_board.dart';
import 'webshop_products.dart';
import 'content_translations.dart';
import 'events.dart';

class Departments {
  String id;
  String name;
  String campusId;
  Campus? campus;
  List<Users>? users;
  String? logo;
  bool? active;
  String? type;
  List<DepartmentSocials>? socials;
  List<News>? news;
  List<Jobs>? jobs;
  List<DepartmentBoard>? boardMembers;
  List<WebshopProducts>? products;
  List<ContentTranslations>? translations;
  String? hero;
  List<Events>? events;

  Departments({
    required this.id,
    required this.name,
    required this.campusId,
    this.campus,
    this.users,
    this.logo,
    this.active,
    this.type,
    this.socials,
    this.news,
    this.jobs,
    this.boardMembers,
    this.products,
    this.translations,
    this.hero,
    this.events
  });

  factory Departments.fromMap(Map<String, dynamic> map) {
    return Departments(
  id: map['Id'].toString(),
  name: map['Name'].toString(),
  campusId: map['campus_id'].toString(),
  campus: map['campus'] != null ? Campus.fromMap(map['campus']) : null,
  users: (map['users'] as List<dynamic>?)?.map((e) => Users.fromMap(e)).toList()
,
  logo: map['logo']?.toString(),
  active: map['active'],
  type: map['type']?.toString(),
  socials: (map['socials'] as List<dynamic>?)?.map((e) => DepartmentSocials.fromMap(e)).toList()
,
  news: (map['news'] as List<dynamic>?)?.map((e) => News.fromMap(e)).toList()
,
  jobs: (map['jobs'] as List<dynamic>?)?.map((e) => Jobs.fromMap(e)).toList()
,
  boardMembers: (map['boardMembers'] as List<dynamic>?)?.map((e) => DepartmentBoard.fromMap(e)).toList()
,
  products: (map['products'] as List<dynamic>?)?.map((e) => WebshopProducts.fromMap(e)).toList()
,
  translations: (map['translations'] as List<dynamic>?)?.map((e) => ContentTranslations.fromMap(e)).toList()
,
  hero: map['hero']?.toString(),
  events: (map['events'] as List<dynamic>?)?.map((e) => Events.fromMap(e)).toList()

    );
  }

  Map<String, dynamic> toMap() {
    return {
  'Id': id,
  'Name': name,
  'campus_id': campusId,
  'campus': campus?.toMap(),
  'users': users?.map((e) => e.toMap()).toList()
,
  'logo': logo,
  'active': active,
  'type': type,
  'socials': socials?.map((e) => e.toMap()).toList()
,
  'news': news?.map((e) => e.toMap()).toList()
,
  'jobs': jobs?.map((e) => e.toMap()).toList()
,
  'boardMembers': boardMembers?.map((e) => e.toMap()).toList()
,
  'products': products?.map((e) => e.toMap()).toList()
,
  'translations': translations?.map((e) => e.toMap()).toList()
,
  'hero': hero,
  'events': events?.map((e) => e.toMap()).toList()

    };
  }
}
