// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

class DepartmentSocials {
  String departmentId;
  String? platform;
  String? url;

  DepartmentSocials({
    required this.departmentId,
    this.platform,
    this.url
  });

  factory DepartmentSocials.fromMap(Map<String, dynamic> map) {
    return DepartmentSocials(
  departmentId: map['department_id'].toString(),
  platform: map['platform']?.toString(),
  url: map['url']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'department_id': departmentId,
  'platform': platform,
  'url': url
    };
  }
}
