// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'departments.dart';

class DepartmentBoard {
  String? name;
  String? imageUrl;
  String? role;
  Departments? department;

  DepartmentBoard({
    this.name,
    this.imageUrl,
    this.role,
    this.department
  });

  factory DepartmentBoard.fromMap(Map<String, dynamic> map) {
    return DepartmentBoard(
  name: map['name']?.toString(),
  imageUrl: map['imageUrl']?.toString(),
  role: map['role']?.toString(),
  department: map['department'] != null ? Departments.fromMap(map['department']) : null
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'name': name,
  'imageUrl': imageUrl,
  'role': role,
  'department': department?.toMap()
    };
  }
}
