// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'campus.dart';
import 'content_translations.dart';
import 'departments.dart';

enum Status {
  draft,
  published,
  cancelled
}

enum CollectionPricing {
  bundle,
  individual
}

class Events {
  Status status;
  String campusId;
  String? slug;
  String? metadata;
  Campus? campus;
  List<ContentTranslations>? translationRefs;
  String? startDate;
  String? endDate;
  String? image;
  String? ticketUrl;
  double? price;
  bool? memberOnly;
  String? collectionId;
  bool? isCollection;
  CollectionPricing? collectionPricing;
  String? location;
  String? departmentId;
  Departments? department;

  Events({
    required this.status,
    required this.campusId,
    this.slug,
    this.metadata,
    this.campus,
    this.translationRefs,
    this.startDate,
    this.endDate,
    this.image,
    this.ticketUrl,
    this.price,
    this.memberOnly,
    this.collectionId,
    this.isCollection,
    this.collectionPricing,
    this.location,
    this.departmentId,
    this.department
  });

  factory Events.fromMap(Map<String, dynamic> map) {
    return Events(
  status: Status.values.firstWhere((e) => e.name == map['status']),
  campusId: map['campus_id'].toString(),
  slug: map['slug']?.toString(),
  metadata: map['metadata']?.toString(),
  campus: map['campus'] != null ? Campus.fromMap(map['campus']) : null,
  translationRefs: (map['translation_refs'] as List<dynamic>?)?.map((e) => ContentTranslations.fromMap(e)).toList()
,
  startDate: map['start_date']?.toString(),
  endDate: map['end_date']?.toString(),
  image: map['image']?.toString(),
  ticketUrl: map['ticket_url']?.toString(),
  price: map['price'],
  memberOnly: map['member_only'],
  collectionId: map['collection_id']?.toString(),
  isCollection: map['is_collection'],
  collectionPricing: map['collection_pricing'] != null ? CollectionPricing.values.where((e) => e.name == map['collection_pricing']).firstOrNull : null,
  location: map['location']?.toString(),
  departmentId: map['department_id']?.toString(),
  department: map['department'] != null ? Departments.fromMap(map['department']) : null
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'status': status.name,
  'campus_id': campusId,
  'slug': slug,
  'metadata': metadata,
  'campus': campus?.toMap(),
  'translation_refs': translationRefs?.map((e) => e.toMap()).toList()
,
  'start_date': startDate,
  'end_date': endDate,
  'image': image,
  'ticket_url': ticketUrl,
  'price': price,
  'member_only': memberOnly,
  'collection_id': collectionId,
  'is_collection': isCollection,
  'collection_pricing': collectionPricing?.name,
  'location': location,
  'department_id': departmentId,
  'department': department?.toMap()
    };
  }
}
