// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'expense_attachments.dart';
import 'users.dart';
import 'departments.dart';
import 'campus.dart';

enum Status {
  draft,
  pending,
  success,
  submitted,
  rejected
}

class Expenses {
  String campus;
  String department;
  String bankAccount;
  double total;
  String userId;
  String? description;
  List<ExpenseAttachments>? expenseAttachments;
  double? prepaymentAmount;
  Status? status;
  int? invoiceId;
  Users? user;
  String? eventName;
  Departments? departmentRel;
  Campus? campusRel;

  Expenses({
    required this.campus,
    required this.department,
    required this.bankAccount,
    required this.total,
    required this.userId,
    this.description,
    this.expenseAttachments,
    this.prepaymentAmount,
    this.status,
    this.invoiceId,
    this.user,
    this.eventName,
    this.departmentRel,
    this.campusRel
  });

  factory Expenses.fromMap(Map<String, dynamic> map) {
    return Expenses(
  campus: map['campus'].toString(),
  department: map['department'].toString(),
  bankAccount: map['bank_account'].toString(),
  total: map['total'],
  userId: map['userId'].toString(),
  description: map['description']?.toString(),
  expenseAttachments: (map['expenseAttachments'] as List<dynamic>?)?.map((e) => ExpenseAttachments.fromMap(e)).toList()
,
  prepaymentAmount: map['prepayment_amount'],
  status: map['status'] != null ? Status.values.where((e) => e.name == map['status']).firstOrNull : null,
  invoiceId: map['invoice_id'],
  user: map['user'] != null ? Users.fromMap(map['user']) : null,
  eventName: map['eventName']?.toString(),
  departmentRel: map['departmentRel'] != null ? Departments.fromMap(map['departmentRel']) : null,
  campusRel: map['campusRel'] != null ? Campus.fromMap(map['campusRel']) : null
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'campus': campus,
  'department': department,
  'bank_account': bankAccount,
  'total': total,
  'userId': userId,
  'description': description,
  'expenseAttachments': expenseAttachments?.map((e) => e.toMap()).toList()
,
  'prepayment_amount': prepaymentAmount,
  'status': status?.name,
  'invoice_id': invoiceId,
  'user': user?.toMap(),
  'eventName': eventName,
  'departmentRel': departmentRel?.toMap(),
  'campusRel': campusRel?.toMap()
    };
  }
}
