// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

class FollowedUnits {
  String userId;
  List<String>? departmentIds;

  FollowedUnits({
    required this.userId,
    this.departmentIds
  });

  factory FollowedUnits.fromMap(Map<String, dynamic> map) {
    return FollowedUnits(
  userId: map['user_id'].toString(),
  departmentIds: List<String>.from(map['department_ids'] ?? [])
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'user_id': userId,
  'department_ids': departmentIds
    };
  }
}
