// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

class FundingPrograms {
  String slug;
  String? status;
  String? heroImageUrl;
  String? applicationUrl;
  String? documentUrl;
  String? contactName;
  String? contactEmail;
  String? contactPhone;
  String? metadata;

  FundingPrograms({
    required this.slug,
    this.status,
    this.heroImageUrl,
    this.applicationUrl,
    this.documentUrl,
    this.contactName,
    this.contactEmail,
    this.contactPhone,
    this.metadata
  });

  factory FundingPrograms.fromMap(Map<String, dynamic> map) {
    return FundingPrograms(
  slug: map['slug'].toString(),
  status: map['status']?.toString(),
  heroImageUrl: map['hero_image_url']?.toString(),
  applicationUrl: map['application_url']?.toString(),
  documentUrl: map['document_url']?.toString(),
  contactName: map['contact_name']?.toString(),
  contactEmail: map['contact_email']?.toString(),
  contactPhone: map['contact_phone']?.toString(),
  metadata: map['metadata']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'slug': slug,
  'status': status,
  'hero_image_url': heroImageUrl,
  'application_url': applicationUrl,
  'document_url': documentUrl,
  'contact_name': contactName,
  'contact_email': contactEmail,
  'contact_phone': contactPhone,
  'metadata': metadata
    };
  }
}
