// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

enum Status {
  submitted,
  reviewed,
  interview,
  accepted,
  rejected
}

class JobApplications {
  String jobId;
  String applicantName;
  String applicantEmail;
  Status status;
  bool gdprConsent;
  String consentDate;
  String dataProcessingPurpose;
  String dataRetentionUntil;
  String? applicantPhone;
  String? coverLetter;
  String? resumeFileId;

  JobApplications({
    required this.jobId,
    required this.applicantName,
    required this.applicantEmail,
    required this.status,
    required this.gdprConsent,
    required this.consentDate,
    required this.dataProcessingPurpose,
    required this.dataRetentionUntil,
    this.applicantPhone,
    this.coverLetter,
    this.resumeFileId
  });

  factory JobApplications.fromMap(Map<String, dynamic> map) {
    return JobApplications(
  jobId: map['job_id'].toString(),
  applicantName: map['applicant_name'].toString(),
  applicantEmail: map['applicant_email'].toString(),
  status: Status.values.firstWhere((e) => e.name == map['status']),
  gdprConsent: map['gdpr_consent'],
  consentDate: map['consent_date'].toString(),
  dataProcessingPurpose: map['data_processing_purpose'].toString(),
  dataRetentionUntil: map['data_retention_until'].toString(),
  applicantPhone: map['applicant_phone']?.toString(),
  coverLetter: map['cover_letter']?.toString(),
  resumeFileId: map['resume_file_id']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'job_id': jobId,
  'applicant_name': applicantName,
  'applicant_email': applicantEmail,
  'status': status.name,
  'gdpr_consent': gdprConsent,
  'consent_date': consentDate,
  'data_processing_purpose': dataProcessingPurpose,
  'data_retention_until': dataRetentionUntil,
  'applicant_phone': applicantPhone,
  'cover_letter': coverLetter,
  'resume_file_id': resumeFileId
    };
  }
}
