// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'campus.dart';
import 'content_translations.dart';
import 'departments.dart';

enum Status {
  draft,
  published,
  closed
}

class Jobs {
  String slug;
  Status status;
  String campusId;
  String? departmentId;
  String? metadata;
  Campus? campus;
  List<ContentTranslations>? translations;
  List<ContentTranslations>? translationRefs;
  Departments? department;

  Jobs({
    required this.slug,
    required this.status,
    required this.campusId,
    this.departmentId,
    this.metadata,
    this.campus,
    this.translations,
    this.translationRefs,
    this.department
  });

  factory Jobs.fromMap(Map<String, dynamic> map) {
    return Jobs(
  slug: map['slug'].toString(),
  status: Status.values.firstWhere((e) => e.name == map['status']),
  campusId: map['campus_id'].toString(),
  departmentId: map['department_id']?.toString(),
  metadata: map['metadata']?.toString(),
  campus: map['campus'] != null ? Campus.fromMap(map['campus']) : null,
  translations: (map['translations'] as List<dynamic>?)?.map((e) => ContentTranslations.fromMap(e)).toList()
,
  translationRefs: (map['translation_refs'] as List<dynamic>?)?.map((e) => ContentTranslations.fromMap(e)).toList()
,
  department: map['department'] != null ? Departments.fromMap(map['department']) : null
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'slug': slug,
  'status': status.name,
  'campus_id': campusId,
  'department_id': departmentId,
  'metadata': metadata,
  'campus': campus?.toMap(),
  'translations': translations?.map((e) => e.toMap()).toList()
,
  'translation_refs': translationRefs?.map((e) => e.toMap()).toList()
,
  'department': department?.toMap()
    };
  }
}
