// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'large_event.dart';

class LargeEventItem {
  String campusId;
  String title;
  String startTime;
  LargeEvent? eventId;
  String? subtitle;
  String? endTime;
  String? coverImageUrl;
  String? location;
  String? ticketUrl;
  int? sort;

  LargeEventItem({
    required this.campusId,
    required this.title,
    required this.startTime,
    this.eventId,
    this.subtitle,
    this.endTime,
    this.coverImageUrl,
    this.location,
    this.ticketUrl,
    this.sort
  });

  factory LargeEventItem.fromMap(Map<String, dynamic> map) {
    return LargeEventItem(
  campusId: map['campusId'].toString(),
  title: map['title'].toString(),
  startTime: map['startTime'].toString(),
  eventId: map['eventId'] != null ? LargeEvent.fromMap(map['eventId']) : null,
  subtitle: map['subtitle']?.toString(),
  endTime: map['endTime']?.toString(),
  coverImageUrl: map['coverImageUrl']?.toString(),
  location: map['location']?.toString(),
  ticketUrl: map['ticketUrl']?.toString(),
  sort: map['sort']
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'campusId': campusId,
  'title': title,
  'startTime': startTime,
  'eventId': eventId?.toMap(),
  'subtitle': subtitle,
  'endTime': endTime,
  'coverImageUrl': coverImageUrl,
  'location': location,
  'ticketUrl': ticketUrl,
  'sort': sort
    };
  }
}
