// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'student_ids.dart';
import 'payments.dart';

class Memberships {
  String membershipId;
  String name;
  double price;
  bool status;
  String expiryDate;
  bool canPurchase;
  String startDate;
  List<StudentIds>? studentId;
  List<Payments>? payments;
  String? category;

  Memberships({
    required this.membershipId,
    required this.name,
    required this.price,
    required this.status,
    required this.expiryDate,
    required this.canPurchase,
    required this.startDate,
    this.studentId,
    this.payments,
    this.category
  });

  factory Memberships.fromMap(Map<String, dynamic> map) {
    return Memberships(
  membershipId: map['membership_id'].toString(),
  name: map['name'].toString(),
  price: map['price'],
  status: map['status'],
  expiryDate: map['expiryDate'].toString(),
  canPurchase: map['canPurchase'],
  startDate: map['startDate'].toString(),
  studentId: (map['studentId'] as List<dynamic>?)?.map((e) => StudentIds.fromMap(e)).toList()
,
  payments: (map['payments'] as List<dynamic>?)?.map((e) => Payments.fromMap(e)).toList()
,
  category: map['category']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'membership_id': membershipId,
  'name': name,
  'price': price,
  'status': status,
  'expiryDate': expiryDate,
  'canPurchase': canPurchase,
  'startDate': startDate,
  'studentId': studentId?.map((e) => e.toMap()).toList()
,
  'payments': payments?.map((e) => e.toMap()).toList()
,
  'category': category
    };
  }
}
