// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'content_translations.dart';

class MemberBenefit {
  List<ContentTranslations>? contentTranslations;

  MemberBenefit({
    this.contentTranslations
  });

  factory MemberBenefit.fromMap(Map<String, dynamic> map) {
    return MemberBenefit(
  contentTranslations: (map['contentTranslations'] as List<dynamic>?)?.map((e) => ContentTranslations.fromMap(e)).toList()

    );
  }

  Map<String, dynamic> toMap() {
    return {
  'contentTranslations': contentTranslations?.map((e) => e.toMap()).toList()

    };
  }
}
