// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'campus.dart';
import 'content_translations.dart';
import 'departments.dart';

enum Status {
  draft,
  published
}

class News {
  Status status;
  String campusId;
  String? slug;
  String? departmentId;
  bool? sticky;
  Campus? campus;
  List<ContentTranslations>? translationRefs;
  String? url;
  String? image;
  Departments? department;
  List<String>? metadata;
  String? author;

  News({
    required this.status,
    required this.campusId,
    this.slug,
    this.departmentId,
    this.sticky,
    this.campus,
    this.translationRefs,
    this.url,
    this.image,
    this.department,
    this.metadata,
    this.author
  });

  factory News.fromMap(Map<String, dynamic> map) {
    return News(
  status: Status.values.firstWhere((e) => e.name == map['status']),
  campusId: map['campus_id'].toString(),
  slug: map['slug']?.toString(),
  departmentId: map['department_id']?.toString(),
  sticky: map['sticky'],
  campus: map['campus'] != null ? Campus.fromMap(map['campus']) : null,
  translationRefs: (map['translation_refs'] as List<dynamic>?)?.map((e) => ContentTranslations.fromMap(e)).toList()
,
  url: map['url']?.toString(),
  image: map['image']?.toString(),
  department: map['department'] != null ? Departments.fromMap(map['department']) : null,
  metadata: List<String>.from(map['metadata'] ?? []),
  author: map['author']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'status': status.name,
  'campus_id': campusId,
  'slug': slug,
  'department_id': departmentId,
  'sticky': sticky,
  'campus': campus?.toMap(),
  'translation_refs': translationRefs?.map((e) => e.toMap()).toList()
,
  'url': url,
  'image': image,
  'department': department?.toMap(),
  'metadata': metadata,
  'author': author
    };
  }
}
