// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

enum Status {
  read,
  unread
}

class Notifications {
  Status? status;

  Notifications({
    this.status
  });

  factory Notifications.fromMap(Map<String, dynamic> map) {
    return Notifications(
  status: map['status'] != null ? Status.values.where((e) => e.name == map['status']).firstOrNull : null
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'status': status?.name
    };
  }
}
