// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

enum Currency {
  nok
}

enum Status {
  pending,
  authorized,
  paid,
  cancelled,
  failed,
  refunded
}

class Orders {
  double subtotal;
  double total;
  Currency currency;
  Status? status;
  String? userId;
  String? buyerName;
  String? buyerEmail;
  String? buyerPhone;
  double? discountTotal;
  String? itemsJson;
  bool? membershipApplied;
  double? memberDiscountPercent;
  String? vippsSessionId;
  String? vippsOrderId;
  String? vippsPaymentLink;
  String? vippsReceiptUrl;
  String? campusId;

  Orders({
    required this.subtotal,
    required this.total,
    required this.currency,
    this.status,
    this.userId,
    this.buyerName,
    this.buyerEmail,
    this.buyerPhone,
    this.discountTotal,
    this.itemsJson,
    this.membershipApplied,
    this.memberDiscountPercent,
    this.vippsSessionId,
    this.vippsOrderId,
    this.vippsPaymentLink,
    this.vippsReceiptUrl,
    this.campusId
  });

  factory Orders.fromMap(Map<String, dynamic> map) {
    return Orders(
  subtotal: map['subtotal'],
  total: map['total'],
  currency: Currency.values.firstWhere((e) => e.name == map['currency']),
  status: map['status'] != null ? Status.values.where((e) => e.name == map['status']).firstOrNull : null,
  userId: map['userId']?.toString(),
  buyerName: map['buyer_name']?.toString(),
  buyerEmail: map['buyer_email']?.toString(),
  buyerPhone: map['buyer_phone']?.toString(),
  discountTotal: map['discount_total'],
  itemsJson: map['items_json']?.toString(),
  membershipApplied: map['membership_applied'],
  memberDiscountPercent: map['member_discount_percent'],
  vippsSessionId: map['vipps_session_id']?.toString(),
  vippsOrderId: map['vipps_order_id']?.toString(),
  vippsPaymentLink: map['vipps_payment_link']?.toString(),
  vippsReceiptUrl: map['vipps_receipt_url']?.toString(),
  campusId: map['campus_id']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'subtotal': subtotal,
  'total': total,
  'currency': currency.name,
  'status': status?.name,
  'userId': userId,
  'buyer_name': buyerName,
  'buyer_email': buyerEmail,
  'buyer_phone': buyerPhone,
  'discount_total': discountTotal,
  'items_json': itemsJson,
  'membership_applied': membershipApplied,
  'member_discount_percent': memberDiscountPercent,
  'vipps_session_id': vippsSessionId,
  'vipps_order_id': vippsOrderId,
  'vipps_payment_link': vippsPaymentLink,
  'vipps_receipt_url': vippsReceiptUrl,
  'campus_id': campusId
    };
  }
}
