// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

enum Locale {
  en,
  no
}

class PageViewEvents {
  String path;
  Locale? locale;
  String? referrer;
  String? userAgent;
  String? visitorIp;
  String? userId;

  PageViewEvents({
    required this.path,
    this.locale,
    this.referrer,
    this.userAgent,
    this.visitorIp,
    this.userId
  });

  factory PageViewEvents.fromMap(Map<String, dynamic> map) {
    return PageViewEvents(
  path: map['path'].toString(),
  locale: map['locale'] != null ? Locale.values.where((e) => e.name == map['locale']).firstOrNull : null,
  referrer: map['referrer']?.toString(),
  userAgent: map['user_agent']?.toString(),
  visitorIp: map['visitor_ip']?.toString(),
  userId: map['user_id']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'path': path,
  'locale': locale?.name,
  'referrer': referrer,
  'user_agent': userAgent,
  'visitor_ip': visitorIp,
  'user_id': userId
    };
  }
}
