// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'pages.dart';

enum Locale {
  no,
  en
}

class PageTranslations {
  String pageId;
  String title;
  Locale? locale;
  String? slug;
  String? description;
  String? puckDocument;
  String? draftDocument;
  bool? isPublished;
  String? publishedAt;
  Pages? page;

  PageTranslations({
    required this.pageId,
    required this.title,
    this.locale,
    this.slug,
    this.description,
    this.puckDocument,
    this.draftDocument,
    this.isPublished,
    this.publishedAt,
    this.page
  });

  factory PageTranslations.fromMap(Map<String, dynamic> map) {
    return PageTranslations(
  pageId: map['page_id'].toString(),
  title: map['title'].toString(),
  locale: map['locale'] != null ? Locale.values.where((e) => e.name == map['locale']).firstOrNull : null,
  slug: map['slug']?.toString(),
  description: map['description']?.toString(),
  puckDocument: map['puck_document']?.toString(),
  draftDocument: map['draft_document']?.toString(),
  isPublished: map['is_published'],
  publishedAt: map['published_at']?.toString(),
  page: map['page'] != null ? Pages.fromMap(map['page']) : null
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'page_id': pageId,
  'title': title,
  'locale': locale?.name,
  'slug': slug,
  'description': description,
  'puck_document': puckDocument,
  'draft_document': draftDocument,
  'is_published': isPublished,
  'published_at': publishedAt,
  'page': page?.toMap()
    };
  }
}
