// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'campus.dart';
import 'page_translations.dart';

enum Status {
  draft,
  published,
  archived
}

enum Visibility {
  public,
  authenticated
}

class Pages {
  String? slug;
  String? title;
  String? template;
  String? campusId;
  Campus? campus;
  Status? status;
  Visibility? visibility;
  List<PageTranslations>? translationRefs;

  Pages({
    this.slug,
    this.title,
    this.template,
    this.campusId,
    this.campus,
    this.status,
    this.visibility,
    this.translationRefs
  });

  factory Pages.fromMap(Map<String, dynamic> map) {
    return Pages(
  slug: map['slug']?.toString(),
  title: map['title']?.toString(),
  template: map['template']?.toString(),
  campusId: map['campus_id']?.toString(),
  campus: map['campus'] != null ? Campus.fromMap(map['campus']) : null,
  status: map['status'] != null ? Status.values.where((e) => e.name == map['status']).firstOrNull : null,
  visibility: map['visibility'] != null ? Visibility.values.where((e) => e.name == map['visibility']).firstOrNull : null,
  translationRefs: (map['translation_refs'] as List<dynamic>?)?.map((e) => PageTranslations.fromMap(e)).toList()

    );
  }

  Map<String, dynamic> toMap() {
    return {
  'slug': slug,
  'title': title,
  'template': template,
  'campus_id': campusId,
  'campus': campus?.toMap(),
  'status': status?.name,
  'visibility': visibility?.name,
  'translation_refs': translationRefs?.map((e) => e.toMap()).toList()

    };
  }
}
