// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'campus.dart';

enum Level {
  national,
  campus
}

class Partners {
  String name;
  Level level;
  String imageUrl;
  String campusId;
  String? url;
  Campus? campus;

  Partners({
    required this.name,
    required this.level,
    required this.imageUrl,
    required this.campusId,
    this.url,
    this.campus
  });

  factory Partners.fromMap(Map<String, dynamic> map) {
    return Partners(
  name: map['name'].toString(),
  level: Level.values.firstWhere((e) => e.name == map['level']),
  imageUrl: map['image_url'].toString(),
  campusId: map['campus_id'].toString(),
  url: map['url']?.toString(),
  campus: map['campus'] != null ? Campus.fromMap(map['campus']) : null
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'name': name,
  'level': level.name,
  'image_url': imageUrl,
  'campus_id': campusId,
  'url': url,
  'campus': campus?.toMap()
    };
  }
}
