// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'memberships.dart';
import 'users.dart';

class Payments {
  String reference;
  double amount;
  String? description;
  String? membershipId;
  Memberships? membership;
  String? status;
  double? paidAmount;
  Users? user;
  String? paymentMethod;
  String? userId;

  Payments({
    required this.reference,
    required this.amount,
    this.description,
    this.membershipId,
    this.membership,
    this.status,
    this.paidAmount,
    this.user,
    this.paymentMethod,
    this.userId
  });

  factory Payments.fromMap(Map<String, dynamic> map) {
    return Payments(
  reference: map['reference'].toString(),
  amount: map['amount'],
  description: map['description']?.toString(),
  membershipId: map['membership_id']?.toString(),
  membership: map['membership'] != null ? Memberships.fromMap(map['membership']) : null,
  status: map['status']?.toString(),
  paidAmount: map['paid_amount'],
  user: map['user'] != null ? Users.fromMap(map['user']) : null,
  paymentMethod: map['payment_method']?.toString(),
  userId: map['user_id']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'reference': reference,
  'amount': amount,
  'description': description,
  'membership_id': membershipId,
  'membership': membership?.toMap(),
  'status': status,
  'paid_amount': paidAmount,
  'user': user?.toMap(),
  'payment_method': paymentMethod,
  'user_id': userId
    };
  }
}
