// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'product_favorites.dart';

enum Condition {
  brandNew,
  likeNew,
  good,
  fair,
  poor
}

enum Status {
  available,
  sold,
  reserved,
  inactive
}

enum ContactMethod {
  message,
  phone,
  email
}

class Products {
  String name;
  String description;
  double price;
  String currency;
  String sellerId;
  String sellerName;
  String campusId;
  String category;
  Condition condition;
  Status status;
  String? sellerAvatar;
  List<String>? images;
  bool? isNegotiable;
  ContactMethod? contactMethod;
  String? contactInfo;
  int? viewCount;
  int? favoriteCount;
  List<String>? imageFileIds;
  List<ProductFavorites>? favorites;

  Products({
    required this.name,
    required this.description,
    required this.price,
    required this.currency,
    required this.sellerId,
    required this.sellerName,
    required this.campusId,
    required this.category,
    required this.condition,
    required this.status,
    this.sellerAvatar,
    this.images,
    this.isNegotiable,
    this.contactMethod,
    this.contactInfo,
    this.viewCount,
    this.favoriteCount,
    this.imageFileIds,
    this.favorites
  });

  factory Products.fromMap(Map<String, dynamic> map) {
    return Products(
  name: map['name'].toString(),
  description: map['description'].toString(),
  price: map['price'],
  currency: map['currency'].toString(),
  sellerId: map['seller_id'].toString(),
  sellerName: map['seller_name'].toString(),
  campusId: map['campus_id'].toString(),
  category: map['category'].toString(),
  condition: map['condition'] == 'new' 
      ? Condition.brandNew 
      : Condition.values.firstWhere((e) => e.name == map['condition']),
  status: Status.values.firstWhere((e) => e.name == map['status']),
  sellerAvatar: map['seller_avatar']?.toString(),
  images: List<String>.from(map['images'] ?? []),
  isNegotiable: map['is_negotiable'],
  contactMethod: map['contact_method'] != null ? ContactMethod.values.where((e) => e.name == map['contact_method']).firstOrNull : null,
  contactInfo: map['contact_info']?.toString(),
  viewCount: map['view_count'],
  favoriteCount: map['favorite_count'],
  imageFileIds: List<String>.from(map['image_file_ids'] ?? []),
  favorites: (map['favorites'] as List<dynamic>?)?.map((e) => ProductFavorites.fromMap(e)).toList()

    );
  }

  Map<String, dynamic> toMap() {
    return {
  'name': name,
  'description': description,
  'price': price,
  'currency': currency,
  'seller_id': sellerId,
  'seller_name': sellerName,
  'campus_id': campusId,
  'category': category,
  'condition': condition == Condition.brandNew ? 'new' : condition.name,
  'status': status.name,
  'seller_avatar': sellerAvatar,
  'images': images,
  'is_negotiable': isNegotiable,
  'contact_method': contactMethod?.name,
  'contact_info': contactInfo,
  'view_count': viewCount,
  'favorite_count': favoriteCount,
  'image_file_ids': imageFileIds,
  'favorites': favorites?.map((e) => e.toMap()).toList()

    };
  }
}
