// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'products.dart';

class ProductFavorites {
  String userId;
  Products? product;

  ProductFavorites({
    required this.userId,
    this.product
  });

  factory ProductFavorites.fromMap(Map<String, dynamic> map) {
    return ProductFavorites(
  userId: map['user_id'].toString(),
  product: map['product'] != null ? Products.fromMap(map['product']) : null
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'user_id': userId,
  'product': product?.toMap()
    };
  }
}
