// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

class PublicProfiles {
  String userId;
  String name;
  String? email;
  String? phone;
  String? campusId;
  String? avatar;
  bool? emailVisible;
  bool? phoneVisible;

  PublicProfiles({
    required this.userId,
    required this.name,
    this.email,
    this.phone,
    this.campusId,
    this.avatar,
    this.emailVisible,
    this.phoneVisible
  });

  factory PublicProfiles.fromMap(Map<String, dynamic> map) {
    return PublicProfiles(
  userId: map['user_id'].toString(),
  name: map['name'].toString(),
  email: map['email']?.toString(),
  phone: map['phone']?.toString(),
  campusId: map['campus_id']?.toString(),
  avatar: map['avatar']?.toString(),
  emailVisible: map['email_visible'],
  phoneVisible: map['phone_visible']
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'user_id': userId,
  'name': name,
  'email': email,
  'phone': phone,
  'campus_id': campusId,
  'avatar': avatar,
  'email_visible': emailVisible,
  'phone_visible': phoneVisible
    };
  }
}
