// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'memberships.dart';
import 'users.dart';

class StudentIds {
  String studentId;
  String? expiryDate;
  bool? isMember;
  List<Memberships>? memberships;
  List<String>? membershipIds;
  Users? user;

  StudentIds({
    required this.studentId,
    this.expiryDate,
    this.isMember,
    this.memberships,
    this.membershipIds,
    this.user
  });

  factory StudentIds.fromMap(Map<String, dynamic> map) {
    return StudentIds(
  studentId: map['student_id'].toString(),
  expiryDate: map['expiry_date']?.toString(),
  isMember: map['isMember'],
  memberships: (map['memberships'] as List<dynamic>?)?.map((e) => Memberships.fromMap(e)).toList()
,
  membershipIds: List<String>.from(map['membership_ids'] ?? []),
  user: map['user'] != null ? Users.fromMap(map['user']) : null
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'student_id': studentId,
  'expiry_date': expiryDate,
  'isMember': isMember,
  'memberships': memberships?.map((e) => e.toMap()).toList()
,
  'membership_ids': membershipIds,
  'user': user?.toMap()
    };
  }
}
