// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

class Subscriptions {
  String userId;
  String topic;
  bool subscribed;
  String subscriberId;

  Subscriptions({
    required this.userId,
    required this.topic,
    required this.subscribed,
    required this.subscriberId
  });

  factory Subscriptions.fromMap(Map<String, dynamic> map) {
    return Subscriptions(
  userId: map['user_id'].toString(),
  topic: map['topic'].toString(),
  subscribed: map['subscribed'],
  subscriberId: map['subscriber_id'].toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'user_id': userId,
  'topic': topic,
  'subscribed': subscribed,
  'subscriber_id': subscriberId
    };
  }
}
