// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

class TypingIndicators {
  String chatId;
  String userId;
  String userName;
  bool isTyping;
  String expiresAt;

  TypingIndicators({
    required this.chatId,
    required this.userId,
    required this.userName,
    required this.isTyping,
    required this.expiresAt
  });

  factory TypingIndicators.fromMap(Map<String, dynamic> map) {
    return TypingIndicators(
  chatId: map['chat_id'].toString(),
  userId: map['user_id'].toString(),
  userName: map['user_name'].toString(),
  isTyping: map['is_typing'],
  expiresAt: map['expires_at'].toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'chat_id': chatId,
  'user_id': userId,
  'user_name': userName,
  'is_typing': isTyping,
  'expires_at': expiresAt
    };
  }
}
