// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'campus.dart';
import 'departments.dart';
import 'expenses.dart';
import 'payments.dart';
import 'student_ids.dart';
import 'saved_jobs.dart';

class Users {
  String? phone;
  String? address;
  String? city;
  String? zip;
  String? bankAccount;
  String? name;
  String? email;
  Campus? campus;
  List<Departments>? departments;
  List<Expenses>? expenses;
  String? campusId;
  List<String>? departmentIds;
  List<String>? membershipIds;
  String? studentId;
  List<Payments>? payments;
  StudentIds? studentIdDoc;
  String? avatar;
  List<String>? roles;
  bool? isActive;
  String? swift;
  List<SavedJobs>? savedJobs;
  bool? isPublic;
  String? bio;

  Users({
    this.phone,
    this.address,
    this.city,
    this.zip,
    this.bankAccount,
    this.name,
    this.email,
    this.campus,
    this.departments,
    this.expenses,
    this.campusId,
    this.departmentIds,
    this.membershipIds,
    this.studentId,
    this.payments,
    this.studentIdDoc,
    this.avatar,
    this.roles,
    this.isActive,
    this.swift,
    this.savedJobs,
    this.isPublic,
    this.bio
  });

  factory Users.fromMap(Map<String, dynamic> map) {
    return Users(
  phone: map['phone']?.toString(),
  address: map['address']?.toString(),
  city: map['city']?.toString(),
  zip: map['zip']?.toString(),
  bankAccount: map['bank_account']?.toString(),
  name: map['name']?.toString(),
  email: map['email']?.toString(),
  campus: map['campus'] != null ? Campus.fromMap(map['campus']) : null,
  departments: (map['departments'] as List<dynamic>?)?.map((e) => Departments.fromMap(e)).toList()
,
  expenses: (map['expenses'] as List<dynamic>?)?.map((e) => Expenses.fromMap(e)).toList()
,
  campusId: map['campus_id']?.toString(),
  departmentIds: List<String>.from(map['department_ids'] ?? []),
  membershipIds: List<String>.from(map['membership_ids'] ?? []),
  studentId: map['student_id']?.toString(),
  payments: (map['payments'] as List<dynamic>?)?.map((e) => Payments.fromMap(e)).toList()
,
  studentIdDoc: map['studentId'] != null ? StudentIds.fromMap(map['studentId']) : null,
  avatar: map['avatar']?.toString(),
  roles: List<String>.from(map['roles'] ?? []),
  isActive: map['isActive'],
  swift: map['swift']?.toString(),
  savedJobs: (map['savedJobs'] as List<dynamic>?)?.map((e) => SavedJobs.fromMap(e)).toList()
,
  isPublic: map['is_public'],
  bio: map['bio']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'phone': phone,
  'address': address,
  'city': city,
  'zip': zip,
  'bank_account': bankAccount,
  'name': name,
  'email': email,
  'campus': campus?.toMap(),
  'departments': departments?.map((e) => e.toMap()).toList()
,
  'expenses': expenses?.map((e) => e.toMap()).toList()
,
  'campus_id': campusId,
  'department_ids': departmentIds,
  'membership_ids': membershipIds,
  'student_id': studentId,
  'payments': payments?.map((e) => e.toMap()).toList()
,
  'studentId': studentIdDoc?.toMap(),
  'avatar': avatar,
  'roles': roles,
  'isActive': isActive,
  'swift': swift,
  'savedJobs': savedJobs?.map((e) => e.toMap()).toList()
,
  'is_public': isPublic,
  'bio': bio
    };
  }
}
