// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.

class VarslingSettings {
  String campusId;
  String roleName;
  String email;
  int? sortOrder;
  bool? isActive;

  VarslingSettings({
    required this.campusId,
    required this.roleName,
    required this.email,
    this.sortOrder,
    this.isActive
  });

  factory VarslingSettings.fromMap(Map<String, dynamic> map) {
    return VarslingSettings(
  campusId: map['campus_id'].toString(),
  roleName: map['role_name'].toString(),
  email: map['email'].toString(),
  sortOrder: map['sort_order'],
  isActive: map['is_active']
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'campus_id': campusId,
  'role_name': roleName,
  'email': email,
  'sort_order': sortOrder,
  'is_active': isActive
    };
  }
}
