// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l dart -s ./lib/schema/appwrite`.
import 'campus.dart';
import 'content_translations.dart';
import 'departments.dart';

enum Status {
  draft,
  published,
  archived
}

class WebshopProducts {
  String slug;
  Status status;
  String campusId;
  double regularPrice;
  String? metadata;
  Campus? campus;
  List<ContentTranslations>? translationRefs;
  String? departmentId;
  double? memberPrice;
  bool? memberOnly;
  String? category;
  String? image;
  int? stock;
  Departments? department;

  WebshopProducts({
    required this.slug,
    required this.status,
    required this.campusId,
    required this.regularPrice,
    this.metadata,
    this.campus,
    this.translationRefs,
    this.departmentId,
    this.memberPrice,
    this.memberOnly,
    this.category,
    this.image,
    this.stock,
    this.department
  });

  factory WebshopProducts.fromMap(Map<String, dynamic> map) {
    return WebshopProducts(
  slug: map['slug'].toString(),
  status: Status.values.firstWhere((e) => e.name == map['status']),
  campusId: map['campus_id'].toString(),
  regularPrice: map['regular_price'],
  metadata: map['metadata']?.toString(),
  campus: map['campus'] != null ? Campus.fromMap(map['campus']) : null,
  translationRefs: (map['translation_refs'] as List<dynamic>?)?.map((e) => ContentTranslations.fromMap(e)).toList()
,
  departmentId: map['departmentId']?.toString(),
  memberPrice: map['member_price'],
  memberOnly: map['member_only'],
  category: map['category']?.toString(),
  image: map['image']?.toString(),
  stock: map['stock'],
  department: map['department'] != null ? Departments.fromMap(map['department']) : null
    );
  }

  Map<String, dynamic> toMap() {
    return {
  'slug': slug,
  'status': status.name,
  'campus_id': campusId,
  'regular_price': regularPrice,
  'metadata': metadata,
  'campus': campus?.toMap(),
  'translation_refs': translationRefs?.map((e) => e.toMap()).toList()
,
  'departmentId': departmentId,
  'member_price': memberPrice,
  'member_only': memberOnly,
  'category': category,
  'image': image,
  'stock': stock,
  'department': department?.toMap()
    };
  }
}
