// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class TwentyFourSevenOfficeAuthTokens {
  String token;

  TwentyFourSevenOfficeAuthTokens({
    required this.token
  });

  factory TwentyFourSevenOfficeAuthTokens.fromMap(Map<String, dynamic> map) {
    return TwentyFourSevenOfficeAuthTokens(
      token: map['token'].toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'token': token
    };
  }
}
