// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

enum AppNoticesLocale {
  NORWEGIAN("norwegian"),
  ENGLISH("english");

  const AppNoticesLocale(this.value);
  final String value;

  static AppNoticesLocale? fromValue(String? value) {
    if (value == null) return null;
    return AppNoticesLocale.values.firstWhere((element) => element.value == value);
  }
}

class AppNotices {
  String title;
  String description;
  int priority;
  bool isActive;
  AppNoticesLocale locale;
  String? color;
  String? actionUrl;
  String? actionLabel;

  AppNotices({
    required this.title,
    required this.description,
    required this.priority,
    required this.isActive,
    required this.locale,
    this.color,
    this.actionUrl,
    this.actionLabel
  });

  factory AppNotices.fromMap(Map<String, dynamic> map) {
    return AppNotices(
      title: map['title'].toString(),
      description: map['description'].toString(),
      priority: map['priority'],
      isActive: map['isActive'],
      locale: AppNoticesLocale.values.firstWhere((e) => e.value == map['locale']),
      color: map['color']?.toString(),
      actionUrl: map['actionUrl']?.toString(),
      actionLabel: map['actionLabel']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'title': title,
      'description': description,
      'priority': priority,
      'isActive': isActive,
      'locale': locale.value,
      'color': color,
      'actionUrl': actionUrl,
      'actionLabel': actionLabel
    };
  }
}
