// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class AuditLogs {
  String action;
  String? actor_id;
  String? actor_email;
  String? resource_id;
  String? resource_type;
  String? payload;

  AuditLogs({
    required this.action,
    this.actor_id,
    this.actor_email,
    this.resource_id,
    this.resource_type,
    this.payload
  });

  factory AuditLogs.fromMap(Map<String, dynamic> map) {
    return AuditLogs(
      action: map['action'].toString(),
      actor_id: map['actor_id']?.toString(),
      actor_email: map['actor_email']?.toString(),
      resource_id: map['resource_id']?.toString(),
      resource_type: map['resource_type']?.toString(),
      payload: map['payload']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'action': action,
      'actor_id': actor_id,
      'actor_email': actor_email,
      'resource_id': resource_id,
      'resource_type': resource_type,
      'payload': payload
    };
  }
}
