// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

enum BenefitInteractionsAction {
  VIEW("view"),
  SAVE("save"),
  REVEAL("reveal"),
  CLICK("click"),
  REDEEM("redeem");

  const BenefitInteractionsAction(this.value);
  final String value;

  static BenefitInteractionsAction? fromValue(String? value) {
    if (value == null) return null;
    return BenefitInteractionsAction.values.firstWhere((element) => element.value == value);
  }
}

class BenefitInteractions {
  String benefit_id;
  BenefitInteractionsAction action;
  String? user_id;
  String? campus_id;
  String? metadata;

  BenefitInteractions({
    required this.benefit_id,
    required this.action,
    this.user_id,
    this.campus_id,
    this.metadata
  });

  factory BenefitInteractions.fromMap(Map<String, dynamic> map) {
    return BenefitInteractions(
      benefit_id: map['benefit_id'].toString(),
      action: BenefitInteractionsAction.values.firstWhere((e) => e.value == map['action']),
      user_id: map['user_id']?.toString(),
      campus_id: map['campus_id']?.toString(),
      metadata: map['metadata']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'benefit_id': benefit_id,
      'action': action.value,
      'user_id': user_id,
      'campus_id': campus_id,
      'metadata': metadata
    };
  }
}
