// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class BenefitReveals {
  String revealed_at;
  String user_id;
  String benefit_id;

  BenefitReveals({
    required this.revealed_at,
    required this.user_id,
    required this.benefit_id
  });

  factory BenefitReveals.fromMap(Map<String, dynamic> map) {
    return BenefitReveals(
      revealed_at: map['revealed_at'].toString(),
      user_id: map['user_id'].toString(),
      benefit_id: map['benefit_id'].toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'revealed_at': revealed_at,
      'user_id': user_id,
      'benefit_id': benefit_id
    };
  }
}
