// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class BenefitPartners {
  String name;
  String? website_url;
  String? logo_url;
  String? description_nb;
  String? description_en;
  String? campus_id;
  bool? is_active;

  BenefitPartners({
    required this.name,
    this.website_url,
    this.logo_url,
    this.description_nb,
    this.description_en,
    this.campus_id,
    this.is_active
  });

  factory BenefitPartners.fromMap(Map<String, dynamic> map) {
    return BenefitPartners(
      name: map['name'].toString(),
      website_url: map['website_url']?.toString(),
      logo_url: map['logo_url']?.toString(),
      description_nb: map['description_nb']?.toString(),
      description_en: map['description_en']?.toString(),
      campus_id: map['campus_id']?.toString(),
      is_active: map['is_active']
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'website_url': website_url,
      'logo_url': logo_url,
      'description_nb': description_nb,
      'description_en': description_en,
      'campus_id': campus_id,
      'is_active': is_active
    };
  }
}
