// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'users.dart';

class BugReports {
  String user_id;
  String? description;
  Users? user;
  List<String>? images;

  BugReports({
    required this.user_id,
    this.description,
    this.user,
    this.images
  });

  factory BugReports.fromMap(Map<String, dynamic> map) {
    return BugReports(
      user_id: map['user_id'].toString(),
      description: map['description']?.toString(),
      user: map['user'] != null ? Users.fromMap(map['user']) : null,
      images: List<String>.from(map['images'] ?? [])
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'user_id': user_id,
      'description': description,
      'user': user?.toMap(),
      'images': images
    };
  }
}
