// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'department_board.dart';

class CampusData {
  String? description;
  List<String>? businessBenefits;
  List<String>? studentBenefits;
  List<String>? careerAdvantages;
  List<String>? socialNetwork;
  List<String>? safety;
  String? location;
  List<DepartmentBoard>? departmentBoard;
  String? name;
  String? name_en;
  String? name_nb;
  String? description_en;
  String? tagline_nb;
  String? tagline_en;
  List<String>? highlights_nb;
  List<String>? highlights_en;
  List<String>? focusAreas_nb;
  List<String>? focusAreas_en;
  String? services_nb;
  List<String>? studentBenefits_nb;
  List<String>? studentBenefits_en;
  List<String>? careerAdvantages_nb;
  List<String>? careerAdvantages_en;
  List<String>? socialNetwork_nb;
  List<String>? socialNetwork_en;
  List<String>? safety_nb;
  List<String>? safety_en;
  List<String>? businessBenefits_nb;
  List<String>? businessBenefits_en;
  String? description_nb;

  CampusData({
    this.description,
    this.businessBenefits,
    this.studentBenefits,
    this.careerAdvantages,
    this.socialNetwork,
    this.safety,
    this.location,
    this.departmentBoard,
    this.name,
    this.name_en,
    this.name_nb,
    this.description_en,
    this.tagline_nb,
    this.tagline_en,
    this.highlights_nb,
    this.highlights_en,
    this.focusAreas_nb,
    this.focusAreas_en,
    this.services_nb,
    this.studentBenefits_nb,
    this.studentBenefits_en,
    this.careerAdvantages_nb,
    this.careerAdvantages_en,
    this.socialNetwork_nb,
    this.socialNetwork_en,
    this.safety_nb,
    this.safety_en,
    this.businessBenefits_nb,
    this.businessBenefits_en,
    this.description_nb
  });

  factory CampusData.fromMap(Map<String, dynamic> map) {
    return CampusData(
      description: map['description']?.toString(),
      businessBenefits: List<String>.from(map['businessBenefits'] ?? []),
      studentBenefits: List<String>.from(map['studentBenefits'] ?? []),
      careerAdvantages: List<String>.from(map['careerAdvantages'] ?? []),
      socialNetwork: List<String>.from(map['socialNetwork'] ?? []),
      safety: List<String>.from(map['safety'] ?? []),
      location: map['location']?.toString(),
      departmentBoard: (map['departmentBoard'] as List<dynamic>?)?.map((e) => DepartmentBoard.fromMap(e)).toList(),
      name: map['name']?.toString(),
      name_en: map['name_en']?.toString(),
      name_nb: map['name_nb']?.toString(),
      description_en: map['description_en']?.toString(),
      tagline_nb: map['tagline_nb']?.toString(),
      tagline_en: map['tagline_en']?.toString(),
      highlights_nb: List<String>.from(map['highlights_nb'] ?? []),
      highlights_en: List<String>.from(map['highlights_en'] ?? []),
      focusAreas_nb: List<String>.from(map['focusAreas_nb'] ?? []),
      focusAreas_en: List<String>.from(map['focusAreas_en'] ?? []),
      services_nb: map['services_nb']?.toString(),
      studentBenefits_nb: List<String>.from(map['studentBenefits_nb'] ?? []),
      studentBenefits_en: List<String>.from(map['studentBenefits_en'] ?? []),
      careerAdvantages_nb: List<String>.from(map['careerAdvantages_nb'] ?? []),
      careerAdvantages_en: List<String>.from(map['careerAdvantages_en'] ?? []),
      socialNetwork_nb: List<String>.from(map['socialNetwork_nb'] ?? []),
      socialNetwork_en: List<String>.from(map['socialNetwork_en'] ?? []),
      safety_nb: List<String>.from(map['safety_nb'] ?? []),
      safety_en: List<String>.from(map['safety_en'] ?? []),
      businessBenefits_nb: List<String>.from(map['businessBenefits_nb'] ?? []),
      businessBenefits_en: List<String>.from(map['businessBenefits_en'] ?? []),
      description_nb: map['description_nb']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'description': description,
      'businessBenefits': businessBenefits,
      'studentBenefits': studentBenefits,
      'careerAdvantages': careerAdvantages,
      'socialNetwork': socialNetwork,
      'safety': safety,
      'location': location,
      'departmentBoard': departmentBoard?.map((e) => e.toMap()).toList(),
      'name': name,
      'name_en': name_en,
      'name_nb': name_nb,
      'description_en': description_en,
      'tagline_nb': tagline_nb,
      'tagline_en': tagline_en,
      'highlights_nb': highlights_nb,
      'highlights_en': highlights_en,
      'focusAreas_nb': focusAreas_nb,
      'focusAreas_en': focusAreas_en,
      'services_nb': services_nb,
      'studentBenefits_nb': studentBenefits_nb,
      'studentBenefits_en': studentBenefits_en,
      'careerAdvantages_nb': careerAdvantages_nb,
      'careerAdvantages_en': careerAdvantages_en,
      'socialNetwork_nb': socialNetwork_nb,
      'socialNetwork_en': socialNetwork_en,
      'safety_nb': safety_nb,
      'safety_en': safety_en,
      'businessBenefits_nb': businessBenefits_nb,
      'businessBenefits_en': businessBenefits_en,
      'description_nb': description_nb
    };
  }
}
