// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'expenses.dart';
import 'departments.dart';
import 'users.dart';
import 'campus_data.dart';
import 'saved_jobs.dart';
import 'jobs.dart';
import 'events.dart';
import 'news.dart';
import 'webshop_products.dart';
import 'partners.dart';
import 'pages.dart';

class Campus {
  String name;
  List<Expenses>? expenses;
  List<Departments>? departments;
  List<Users>? users;
  CampusData? campusData;
  String? email;
  List<SavedJobs>? savedJobs;
  List<Jobs>? jobs;
  List<Events>? events;
  List<News>? news;
  List<WebshopProducts>? webshop_products;
  List<Partners>? partners;
  List<Pages>? pages;

  Campus({
    required this.name,
    this.expenses,
    this.departments,
    this.users,
    this.campusData,
    this.email,
    this.savedJobs,
    this.jobs,
    this.events,
    this.news,
    this.webshop_products,
    this.partners,
    this.pages
  });

  factory Campus.fromMap(Map<String, dynamic> map) {
    return Campus(
      name: map['name'].toString(),
      expenses: (map['expenses'] as List<dynamic>?)?.map((e) => Expenses.fromMap(e)).toList(),
      departments: (map['departments'] as List<dynamic>?)?.map((e) => Departments.fromMap(e)).toList(),
      users: (map['users'] as List<dynamic>?)?.map((e) => Users.fromMap(e)).toList(),
      campusData: map['campusData'] != null ? CampusData.fromMap(map['campusData']) : null,
      email: map['email']?.toString(),
      savedJobs: (map['savedJobs'] as List<dynamic>?)?.map((e) => SavedJobs.fromMap(e)).toList(),
      jobs: (map['jobs'] as List<dynamic>?)?.map((e) => Jobs.fromMap(e)).toList(),
      events: (map['events'] as List<dynamic>?)?.map((e) => Events.fromMap(e)).toList(),
      news: (map['news'] as List<dynamic>?)?.map((e) => News.fromMap(e)).toList(),
      webshop_products: (map['webshop_products'] as List<dynamic>?)?.map((e) => WebshopProducts.fromMap(e)).toList(),
      partners: (map['partners'] as List<dynamic>?)?.map((e) => Partners.fromMap(e)).toList(),
      pages: (map['pages'] as List<dynamic>?)?.map((e) => Pages.fromMap(e)).toList()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'expenses': expenses?.map((e) => e.toMap()).toList(),
      'departments': departments?.map((e) => e.toMap()).toList(),
      'users': users?.map((e) => e.toMap()).toList(),
      'campusData': campusData?.toMap(),
      'email': email,
      'savedJobs': savedJobs?.map((e) => e.toMap()).toList(),
      'jobs': jobs?.map((e) => e.toMap()).toList(),
      'events': events?.map((e) => e.toMap()).toList(),
      'news': news?.map((e) => e.toMap()).toList(),
      'webshop_products': webshop_products?.map((e) => e.toMap()).toList(),
      'partners': partners?.map((e) => e.toMap()).toList(),
      'pages': pages?.map((e) => e.toMap()).toList()
    };
  }
}
