// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class CampusMetadata {
  String campus_id;
  String campus_name;
  String? tagline_nb;
  String? tagline_en;
  String? description_nb;
  String? description_en;
  List<String>? highlights_nb;
  List<String>? highlights_en;
  List<String>? focusAreas_nb;
  List<String>? focusAreas_en;
  String? services_nb;
  String? services_en;

  CampusMetadata({
    required this.campus_id,
    required this.campus_name,
    this.tagline_nb,
    this.tagline_en,
    this.description_nb,
    this.description_en,
    this.highlights_nb,
    this.highlights_en,
    this.focusAreas_nb,
    this.focusAreas_en,
    this.services_nb,
    this.services_en
  });

  factory CampusMetadata.fromMap(Map<String, dynamic> map) {
    return CampusMetadata(
      campus_id: map['campus_id'].toString(),
      campus_name: map['campus_name'].toString(),
      tagline_nb: map['tagline_nb']?.toString(),
      tagline_en: map['tagline_en']?.toString(),
      description_nb: map['description_nb']?.toString(),
      description_en: map['description_en']?.toString(),
      highlights_nb: List<String>.from(map['highlights_nb'] ?? []),
      highlights_en: List<String>.from(map['highlights_en'] ?? []),
      focusAreas_nb: List<String>.from(map['focusAreas_nb'] ?? []),
      focusAreas_en: List<String>.from(map['focusAreas_en'] ?? []),
      services_nb: map['services_nb']?.toString(),
      services_en: map['services_en']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'campus_id': campus_id,
      'campus_name': campus_name,
      'tagline_nb': tagline_nb,
      'tagline_en': tagline_en,
      'description_nb': description_nb,
      'description_en': description_en,
      'highlights_nb': highlights_nb,
      'highlights_en': highlights_en,
      'focusAreas_nb': focusAreas_nb,
      'focusAreas_en': focusAreas_en,
      'services_nb': services_nb,
      'services_en': services_en
    };
  }
}
