// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'content_translations.dart';

enum CampusBenefitsStatus {
  DRAFT("draft"),
  PUBLISHED("published"),
  ARCHIVED("archived");

  const CampusBenefitsStatus(this.value);
  final String value;

  static CampusBenefitsStatus? fromValue(String? value) {
    if (value == null) return null;
    return CampusBenefitsStatus.values.firstWhere((element) => element.value == value);
  }
}

enum CampusBenefitsKind {
  OFFER("offer"),
  PERK("perk"),
  SERVICE("service");

  const CampusBenefitsKind(this.value);
  final String value;

  static CampusBenefitsKind? fromValue(String? value) {
    if (value == null) return null;
    return CampusBenefitsKind.values.firstWhere((element) => element.value == value);
  }
}

enum CampusBenefitsRedemptionType {
  NONE("none"),
  CODE("code"),
  LINK("link"),
  QR("qr"),
  ONSITE("onsite");

  const CampusBenefitsRedemptionType(this.value);
  final String value;

  static CampusBenefitsRedemptionType? fromValue(String? value) {
    if (value == null) return null;
    return CampusBenefitsRedemptionType.values.firstWhere((element) => element.value == value);
  }
}

class CampusBenefits {
  String campus_id;
  CampusBenefitsStatus status;
  CampusBenefitsKind kind;
  CampusBenefitsRedemptionType redemption_type;
  String category;
  String title_nb;
  String title_en;
  String description_nb;
  String description_en;
  List<ContentTranslations>? contentTranslations;
  String? partner_id;
  String? partner_name;
  String? partner_logo_url;
  String? teaser_nb;
  String? teaser_en;
  String? terms_nb;
  String? terms_en;
  String? redemption_value;
  String? image_url;
  bool? is_featured;
  bool? is_member_only;
  String? publish_start;
  String? publish_end;
  int? sort_order;
  String? created_by;
  String? updated_by;

  CampusBenefits({
    required this.campus_id,
    required this.status,
    required this.kind,
    required this.redemption_type,
    required this.category,
    required this.title_nb,
    required this.title_en,
    required this.description_nb,
    required this.description_en,
    this.contentTranslations,
    this.partner_id,
    this.partner_name,
    this.partner_logo_url,
    this.teaser_nb,
    this.teaser_en,
    this.terms_nb,
    this.terms_en,
    this.redemption_value,
    this.image_url,
    this.is_featured,
    this.is_member_only,
    this.publish_start,
    this.publish_end,
    this.sort_order,
    this.created_by,
    this.updated_by
  });

  factory CampusBenefits.fromMap(Map<String, dynamic> map) {
    return CampusBenefits(
      campus_id: map['campus_id'].toString(),
      status: CampusBenefitsStatus.values.firstWhere((e) => e.value == map['status']),
      kind: CampusBenefitsKind.values.firstWhere((e) => e.value == map['kind']),
      redemption_type: CampusBenefitsRedemptionType.values.firstWhere((e) => e.value == map['redemption_type']),
      category: map['category'].toString(),
      title_nb: map['title_nb'].toString(),
      title_en: map['title_en'].toString(),
      description_nb: map['description_nb'].toString(),
      description_en: map['description_en'].toString(),
      contentTranslations: (map['contentTranslations'] as List<dynamic>?)?.map((e) => ContentTranslations.fromMap(e)).toList(),
      partner_id: map['partner_id']?.toString(),
      partner_name: map['partner_name']?.toString(),
      partner_logo_url: map['partner_logo_url']?.toString(),
      teaser_nb: map['teaser_nb']?.toString(),
      teaser_en: map['teaser_en']?.toString(),
      terms_nb: map['terms_nb']?.toString(),
      terms_en: map['terms_en']?.toString(),
      redemption_value: map['redemption_value']?.toString(),
      image_url: map['image_url']?.toString(),
      is_featured: map['is_featured'],
      is_member_only: map['is_member_only'],
      publish_start: map['publish_start']?.toString(),
      publish_end: map['publish_end']?.toString(),
      sort_order: map['sort_order'],
      created_by: map['created_by']?.toString(),
      updated_by: map['updated_by']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'campus_id': campus_id,
      'status': status.value,
      'kind': kind.value,
      'redemption_type': redemption_type.value,
      'category': category,
      'title_nb': title_nb,
      'title_en': title_en,
      'description_nb': description_nb,
      'description_en': description_en,
      'contentTranslations': contentTranslations?.map((e) => e.toMap()).toList(),
      'partner_id': partner_id,
      'partner_name': partner_name,
      'partner_logo_url': partner_logo_url,
      'teaser_nb': teaser_nb,
      'teaser_en': teaser_en,
      'terms_nb': terms_nb,
      'terms_en': terms_en,
      'redemption_value': redemption_value,
      'image_url': image_url,
      'is_featured': is_featured,
      'is_member_only': is_member_only,
      'publish_start': publish_start,
      'publish_end': publish_end,
      'sort_order': sort_order,
      'created_by': created_by,
      'updated_by': updated_by
    };
  }
}
