// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class CampusDataTranslations {
  String entry_id;
  String locale;
  String? name;
  String? description;
  String? location;
  List<String>? studentBenefits;
  List<String>? careerAdvantages;
  List<String>? socialNetwork;
  List<String>? safety;
  List<String>? businessBenefits;
  String? data;

  CampusDataTranslations({
    required this.entry_id,
    required this.locale,
    this.name,
    this.description,
    this.location,
    this.studentBenefits,
    this.careerAdvantages,
    this.socialNetwork,
    this.safety,
    this.businessBenefits,
    this.data
  });

  factory CampusDataTranslations.fromMap(Map<String, dynamic> map) {
    return CampusDataTranslations(
      entry_id: map['entry_id'].toString(),
      locale: map['locale'].toString(),
      name: map['name']?.toString(),
      description: map['description']?.toString(),
      location: map['location']?.toString(),
      studentBenefits: List<String>.from(map['studentBenefits'] ?? []),
      careerAdvantages: List<String>.from(map['careerAdvantages'] ?? []),
      socialNetwork: List<String>.from(map['socialNetwork'] ?? []),
      safety: List<String>.from(map['safety'] ?? []),
      businessBenefits: List<String>.from(map['businessBenefits'] ?? []),
      data: map['data']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'entry_id': entry_id,
      'locale': locale,
      'name': name,
      'description': description,
      'location': location,
      'studentBenefits': studentBenefits,
      'careerAdvantages': careerAdvantages,
      'socialNetwork': socialNetwork,
      'safety': safety,
      'businessBenefits': businessBenefits,
      'data': data
    };
  }
}
