// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class CartReservations {
  String product_id;
  String user_id;
  int quantity;
  String expires_at;

  CartReservations({
    required this.product_id,
    required this.user_id,
    required this.quantity,
    required this.expires_at
  });

  factory CartReservations.fromMap(Map<String, dynamic> map) {
    return CartReservations(
      product_id: map['product_id'].toString(),
      user_id: map['user_id'].toString(),
      quantity: map['quantity'],
      expires_at: map['expires_at'].toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'product_id': product_id,
      'user_id': user_id,
      'quantity': quantity,
      'expires_at': expires_at
    };
  }
}
