// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

enum ChatsType {
  DIRECT("direct"),
  GROUP("group"),
  TEAM("team"),
  DEPARTMENT("department");

  const ChatsType(this.value);
  final String value;

  static ChatsType? fromValue(String? value) {
    if (value == null) return null;
    return ChatsType.values.firstWhere((element) => element.value == value);
  }
}

class Chats {
  String name;
  ChatsType type;
  List<String> participants;
  String? description;
  String? team_id;
  String? department_id;
  bool? is_active;
  bool? is_muted;
  int? unread_count;
  String? last_activity_at;

  Chats({
    required this.name,
    required this.type,
    required this.participants,
    this.description,
    this.team_id,
    this.department_id,
    this.is_active,
    this.is_muted,
    this.unread_count,
    this.last_activity_at
  });

  factory Chats.fromMap(Map<String, dynamic> map) {
    return Chats(
      name: map['name'].toString(),
      type: ChatsType.values.firstWhere((e) => e.value == map['type']),
      participants: List<String>.from(map['participants'] ?? []),
      description: map['description']?.toString(),
      team_id: map['team_id']?.toString(),
      department_id: map['department_id']?.toString(),
      is_active: map['is_active'],
      is_muted: map['is_muted'],
      unread_count: map['unread_count'],
      last_activity_at: map['last_activity_at']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'type': type.value,
      'participants': participants,
      'description': description,
      'team_id': team_id,
      'department_id': department_id,
      'is_active': is_active,
      'is_muted': is_muted,
      'unread_count': unread_count,
      'last_activity_at': last_activity_at
    };
  }
}
