// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

enum ChatMessagesType {
  TEXT("text"),
  IMAGE("image"),
  FILE("file"),
  SYSTEM("system"),
  PRODUCT("product");

  const ChatMessagesType(this.value);
  final String value;

  static ChatMessagesType? fromValue(String? value) {
    if (value == null) return null;
    return ChatMessagesType.values.firstWhere((element) => element.value == value);
  }
}

class ChatMessages {
  String chat_id;
  String sender_id;
  String sender_name;
  String content;
  ChatMessagesType type;
  List<String>? attachments;
  bool? is_edited;
  bool? is_deleted;
  String? reply_to_id;

  ChatMessages({
    required this.chat_id,
    required this.sender_id,
    required this.sender_name,
    required this.content,
    required this.type,
    this.attachments,
    this.is_edited,
    this.is_deleted,
    this.reply_to_id
  });

  factory ChatMessages.fromMap(Map<String, dynamic> map) {
    return ChatMessages(
      chat_id: map['chat_id'].toString(),
      sender_id: map['sender_id'].toString(),
      sender_name: map['sender_name'].toString(),
      content: map['content'].toString(),
      type: ChatMessagesType.values.firstWhere((e) => e.value == map['type']),
      attachments: List<String>.from(map['attachments'] ?? []),
      is_edited: map['is_edited'],
      is_deleted: map['is_deleted'],
      reply_to_id: map['reply_to_id']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'chat_id': chat_id,
      'sender_id': sender_id,
      'sender_name': sender_name,
      'content': content,
      'type': type.value,
      'attachments': attachments,
      'is_edited': is_edited,
      'is_deleted': is_deleted,
      'reply_to_id': reply_to_id
    };
  }
}
