// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

enum ContentEntriesKind {
  PAGE("page"),
  POLICY("policy"),
  ARTICLE("article");

  const ContentEntriesKind(this.value);
  final String value;

  static ContentEntriesKind? fromValue(String? value) {
    if (value == null) return null;
    return ContentEntriesKind.values.firstWhere((element) => element.value == value);
  }
}

enum ContentEntriesStatus {
  DRAFT("draft"),
  PUBLISHED("published"),
  ARCHIVED("archived");

  const ContentEntriesStatus(this.value);
  final String value;

  static ContentEntriesStatus? fromValue(String? value) {
    if (value == null) return null;
    return ContentEntriesStatus.values.firstWhere((element) => element.value == value);
  }
}

enum ContentEntriesVisibility {
  PUBLIC("public"),
  AUTHENTICATED("authenticated");

  const ContentEntriesVisibility(this.value);
  final String value;

  static ContentEntriesVisibility? fromValue(String? value) {
    if (value == null) return null;
    return ContentEntriesVisibility.values.firstWhere((element) => element.value == value);
  }
}

enum ContentEntriesScope {
  GLOBAL("global"),
  CAMPUS("campus"),
  DEPARTMENT("department");

  const ContentEntriesScope(this.value);
  final String value;

  static ContentEntriesScope? fromValue(String? value) {
    if (value == null) return null;
    return ContentEntriesScope.values.firstWhere((element) => element.value == value);
  }
}

enum ContentEntriesSourceLocale {
  NO("no"),
  EN("en");

  const ContentEntriesSourceLocale(this.value);
  final String value;

  static ContentEntriesSourceLocale? fromValue(String? value) {
    if (value == null) return null;
    return ContentEntriesSourceLocale.values.firstWhere((element) => element.value == value);
  }
}

class ContentEntries {
  ContentEntriesKind kind;
  ContentEntriesStatus status;
  ContentEntriesVisibility visibility;
  ContentEntriesScope scope;
  ContentEntriesSourceLocale source_locale;
  String template_id;
  String? path;
  String? campus_id;
  String? department_id;
  String? created_by;

  ContentEntries({
    required this.kind,
    required this.status,
    required this.visibility,
    required this.scope,
    required this.source_locale,
    required this.template_id,
    this.path,
    this.campus_id,
    this.department_id,
    this.created_by
  });

  factory ContentEntries.fromMap(Map<String, dynamic> map) {
    return ContentEntries(
      kind: ContentEntriesKind.values.firstWhere((e) => e.value == map['kind']),
      status: ContentEntriesStatus.values.firstWhere((e) => e.value == map['status']),
      visibility: ContentEntriesVisibility.values.firstWhere((e) => e.value == map['visibility']),
      scope: ContentEntriesScope.values.firstWhere((e) => e.value == map['scope']),
      source_locale: ContentEntriesSourceLocale.values.firstWhere((e) => e.value == map['source_locale']),
      template_id: map['template_id'].toString(),
      path: map['path']?.toString(),
      campus_id: map['campus_id']?.toString(),
      department_id: map['department_id']?.toString(),
      created_by: map['created_by']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'kind': kind.value,
      'status': status.value,
      'visibility': visibility.value,
      'scope': scope.value,
      'source_locale': source_locale.value,
      'template_id': template_id,
      'path': path,
      'campus_id': campus_id,
      'department_id': department_id,
      'created_by': created_by
    };
  }
}
