// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'departments.dart';
import 'jobs.dart';
import 'events.dart';
import 'news.dart';
import 'webshop_products.dart';
import 'campus_benefits.dart';

enum ContentTranslationsLocale {
  EN("en"),
  NO("no");

  const ContentTranslationsLocale(this.value);
  final String value;

  static ContentTranslationsLocale? fromValue(String? value) {
    if (value == null) return null;
    return ContentTranslationsLocale.values.firstWhere((element) => element.value == value);
  }
}

enum ContentTranslationsContentType {
  JOB("job"),
  EVENT("event"),
  NEWS("news"),
  PRODUCT("product"),
  DEPARTMENT("department"),
  MEMBER_BENEFIT("memberBenefit"),
  PAGE("page");

  const ContentTranslationsContentType(this.value);
  final String value;

  static ContentTranslationsContentType? fromValue(String? value) {
    if (value == null) return null;
    return ContentTranslationsContentType.values.firstWhere((element) => element.value == value);
  }
}

class ContentTranslations {
  String content_id;
  ContentTranslationsLocale locale;
  String title;
  String description;
  ContentTranslationsContentType content_type;
  Departments? department_ref;
  String? additional_fields;
  Jobs? job_ref;
  String? short_description;
  Events? event_ref;
  News? news_ref;
  WebshopProducts? product_ref;
  CampusBenefits? memberBenefit;

  ContentTranslations({
    required this.content_id,
    required this.locale,
    required this.title,
    required this.description,
    required this.content_type,
    this.department_ref,
    this.additional_fields,
    this.job_ref,
    this.short_description,
    this.event_ref,
    this.news_ref,
    this.product_ref,
    this.memberBenefit
  });

  factory ContentTranslations.fromMap(Map<String, dynamic> map) {
    return ContentTranslations(
      content_id: map['content_id'].toString(),
      locale: ContentTranslationsLocale.values.firstWhere((e) => e.value == map['locale']),
      title: map['title'].toString(),
      description: map['description'].toString(),
      content_type: ContentTranslationsContentType.values.firstWhere((e) => e.value == map['content_type']),
      department_ref: map['department_ref'] != null ? Departments.fromMap(map['department_ref']) : null,
      additional_fields: map['additional_fields']?.toString(),
      job_ref: map['job_ref'] != null ? Jobs.fromMap(map['job_ref']) : null,
      short_description: map['short_description']?.toString(),
      event_ref: map['event_ref'] != null ? Events.fromMap(map['event_ref']) : null,
      news_ref: map['news_ref'] != null ? News.fromMap(map['news_ref']) : null,
      product_ref: map['product_ref'] != null ? WebshopProducts.fromMap(map['product_ref']) : null,
      memberBenefit: map['memberBenefit'] != null ? CampusBenefits.fromMap(map['memberBenefit']) : null
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'content_id': content_id,
      'locale': locale.value,
      'title': title,
      'description': description,
      'content_type': content_type.value,
      'department_ref': department_ref?.toMap(),
      'additional_fields': additional_fields,
      'job_ref': job_ref?.toMap(),
      'short_description': short_description,
      'event_ref': event_ref?.toMap(),
      'news_ref': news_ref?.toMap(),
      'product_ref': product_ref?.toMap(),
      'memberBenefit': memberBenefit?.toMap()
    };
  }
}
