// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

enum ContentTemplatesFamily {
  PAGE("page"),
  POLICY("policy"),
  ARTICLE("article");

  const ContentTemplatesFamily(this.value);
  final String value;

  static ContentTemplatesFamily? fromValue(String? value) {
    if (value == null) return null;
    return ContentTemplatesFamily.values.firstWhere((element) => element.value == value);
  }
}

class ContentTemplates {
  String key;
  String name;
  ContentTemplatesFamily family;
  String? description;
  String? created_by;
  String? current_draft_version_id;
  String? current_published_version_id;

  ContentTemplates({
    required this.key,
    required this.name,
    required this.family,
    this.description,
    this.created_by,
    this.current_draft_version_id,
    this.current_published_version_id
  });

  factory ContentTemplates.fromMap(Map<String, dynamic> map) {
    return ContentTemplates(
      key: map['key'].toString(),
      name: map['name'].toString(),
      family: ContentTemplatesFamily.values.firstWhere((e) => e.value == map['family']),
      description: map['description']?.toString(),
      created_by: map['created_by']?.toString(),
      current_draft_version_id: map['current_draft_version_id']?.toString(),
      current_published_version_id: map['current_published_version_id']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'key': key,
      'name': name,
      'family': family.value,
      'description': description,
      'created_by': created_by,
      'current_draft_version_id': current_draft_version_id,
      'current_published_version_id': current_published_version_id
    };
  }
}
