// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

enum ContentEntryLocalesLocale {
  NO("no"),
  EN("en");

  const ContentEntryLocalesLocale(this.value);
  final String value;

  static ContentEntryLocalesLocale? fromValue(String? value) {
    if (value == null) return null;
    return ContentEntryLocalesLocale.values.firstWhere((element) => element.value == value);
  }
}

enum ContentEntryLocalesTranslationStatus {
  SOURCE("source"),
  MANUAL("manual"),
  AI("ai"),
  STALE("stale");

  const ContentEntryLocalesTranslationStatus(this.value);
  final String value;

  static ContentEntryLocalesTranslationStatus? fromValue(String? value) {
    if (value == null) return null;
    return ContentEntryLocalesTranslationStatus.values.firstWhere((element) => element.value == value);
  }
}

enum ContentEntryLocalesTranslatedFromLocale {
  NO("no"),
  EN("en");

  const ContentEntryLocalesTranslatedFromLocale(this.value);
  final String value;

  static ContentEntryLocalesTranslatedFromLocale? fromValue(String? value) {
    if (value == null) return null;
    return ContentEntryLocalesTranslatedFromLocale.values.firstWhere((element) => element.value == value);
  }
}

class ContentEntryLocales {
  String entry_id;
  ContentEntryLocalesLocale locale;
  String title;
  ContentEntryLocalesTranslationStatus translation_status;
  String? description;
  String? field_values;
  String? seo;
  ContentEntryLocalesTranslatedFromLocale? translated_from_locale;
  String? source_updated_at;

  ContentEntryLocales({
    required this.entry_id,
    required this.locale,
    required this.title,
    required this.translation_status,
    this.description,
    this.field_values,
    this.seo,
    this.translated_from_locale,
    this.source_updated_at
  });

  factory ContentEntryLocales.fromMap(Map<String, dynamic> map) {
    return ContentEntryLocales(
      entry_id: map['entry_id'].toString(),
      locale: ContentEntryLocalesLocale.values.firstWhere((e) => e.value == map['locale']),
      title: map['title'].toString(),
      translation_status: ContentEntryLocalesTranslationStatus.values.firstWhere((e) => e.value == map['translation_status']),
      description: map['description']?.toString(),
      field_values: map['field_values']?.toString(),
      seo: map['seo']?.toString(),
      translated_from_locale: ContentEntryLocalesTranslatedFromLocale.fromValue(map['translated_from_locale']),
      source_updated_at: map['source_updated_at']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'entry_id': entry_id,
      'locale': locale.value,
      'title': title,
      'translation_status': translation_status.value,
      'description': description,
      'field_values': field_values,
      'seo': seo,
      'translated_from_locale': translated_from_locale?.value,
      'source_updated_at': source_updated_at
    };
  }
}
