// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

enum ContentTemplateVersionsStatus {
  DRAFT("draft"),
  PUBLISHED("published");

  const ContentTemplateVersionsStatus(this.value);
  final String value;

  static ContentTemplateVersionsStatus? fromValue(String? value) {
    if (value == null) return null;
    return ContentTemplateVersionsStatus.values.firstWhere((element) => element.value == value);
  }
}

class ContentTemplateVersions {
  String template_id;
  int version;
  String layout_document;
  String field_schema;
  String bindings;
  ContentTemplateVersionsStatus? status;
  String? preview_seed_data;
  String? notes;
  String? published_at;

  ContentTemplateVersions({
    required this.template_id,
    required this.version,
    required this.layout_document,
    required this.field_schema,
    required this.bindings,
    this.status,
    this.preview_seed_data,
    this.notes,
    this.published_at
  });

  factory ContentTemplateVersions.fromMap(Map<String, dynamic> map) {
    return ContentTemplateVersions(
      template_id: map['template_id'].toString(),
      version: map['version'],
      layout_document: map['layout_document'].toString(),
      field_schema: map['field_schema'].toString(),
      bindings: map['bindings'].toString(),
      status: ContentTemplateVersionsStatus.fromValue(map['status']),
      preview_seed_data: map['preview_seed_data']?.toString(),
      notes: map['notes']?.toString(),
      published_at: map['published_at']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'template_id': template_id,
      'version': version,
      'layout_document': layout_document,
      'field_schema': field_schema,
      'bindings': bindings,
      'status': status?.value,
      'preview_seed_data': preview_seed_data,
      'notes': notes,
      'published_at': published_at
    };
  }
}
