// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class DashboardMetrics {
  String metric_type;
  String metric_data;
  String date_range;
  String computed_at;

  DashboardMetrics({
    required this.metric_type,
    required this.metric_data,
    required this.date_range,
    required this.computed_at
  });

  factory DashboardMetrics.fromMap(Map<String, dynamic> map) {
    return DashboardMetrics(
      metric_type: map['metric_type'].toString(),
      metric_data: map['metric_data'].toString(),
      date_range: map['date_range'].toString(),
      computed_at: map['computed_at'].toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'metric_type': metric_type,
      'metric_data': metric_data,
      'date_range': date_range,
      'computed_at': computed_at
    };
  }
}
