// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'departments.dart';

class DepartmentBoard {
  Departments? department;
  String? name;
  String? imageUrl;
  String? role;

  DepartmentBoard({
    this.department,
    this.name,
    this.imageUrl,
    this.role
  });

  factory DepartmentBoard.fromMap(Map<String, dynamic> map) {
    return DepartmentBoard(
      department: map['department'] != null ? Departments.fromMap(map['department']) : null,
      name: map['name']?.toString(),
      imageUrl: map['imageUrl']?.toString(),
      role: map['role']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'department': department?.toMap(),
      'name': name,
      'imageUrl': imageUrl,
      'role': role
    };
  }
}
