// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class DepartmentSocials {
  String department_id;
  String? platform;
  String? url;

  DepartmentSocials({
    required this.department_id,
    this.platform,
    this.url
  });

  factory DepartmentSocials.fromMap(Map<String, dynamic> map) {
    return DepartmentSocials(
      department_id: map['department_id'].toString(),
      platform: map['platform']?.toString(),
      url: map['url']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'department_id': department_id,
      'platform': platform,
      'url': url
    };
  }
}
