// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'users.dart';
import 'department_socials.dart';
import 'department_board.dart';
import 'webshop_products.dart';
import 'content_translations.dart';
import 'campus.dart';
import 'jobs.dart';
import 'events.dart';
import 'news.dart';

class Departments {
  String Id;
  String Name;
  String campus_id;
  List<Users>? users;
  String? logo;
  bool? active;
  String? type;
  List<DepartmentSocials>? socials;
  List<DepartmentBoard>? boardMembers;
  List<WebshopProducts>? products;
  List<ContentTranslations>? translations;
  String? hero;
  Campus? campus;
  List<Jobs>? jobs;
  List<Events>? events;
  List<News>? news;

  Departments({
    required this.Id,
    required this.Name,
    required this.campus_id,
    this.users,
    this.logo,
    this.active,
    this.type,
    this.socials,
    this.boardMembers,
    this.products,
    this.translations,
    this.hero,
    this.campus,
    this.jobs,
    this.events,
    this.news
  });

  factory Departments.fromMap(Map<String, dynamic> map) {
    return Departments(
      Id: map['Id'].toString(),
      Name: map['Name'].toString(),
      campus_id: map['campus_id'].toString(),
      users: (map['users'] as List<dynamic>?)?.map((e) => Users.fromMap(e)).toList(),
      logo: map['logo']?.toString(),
      active: map['active'],
      type: map['type']?.toString(),
      socials: (map['socials'] as List<dynamic>?)?.map((e) => DepartmentSocials.fromMap(e)).toList(),
      boardMembers: (map['boardMembers'] as List<dynamic>?)?.map((e) => DepartmentBoard.fromMap(e)).toList(),
      products: (map['products'] as List<dynamic>?)?.map((e) => WebshopProducts.fromMap(e)).toList(),
      translations: (map['translations'] as List<dynamic>?)?.map((e) => ContentTranslations.fromMap(e)).toList(),
      hero: map['hero']?.toString(),
      campus: map['campus'] != null ? Campus.fromMap(map['campus']) : null,
      jobs: (map['jobs'] as List<dynamic>?)?.map((e) => Jobs.fromMap(e)).toList(),
      events: (map['events'] as List<dynamic>?)?.map((e) => Events.fromMap(e)).toList(),
      news: (map['news'] as List<dynamic>?)?.map((e) => News.fromMap(e)).toList()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'Id': Id,
      'Name': Name,
      'campus_id': campus_id,
      'users': users?.map((e) => e.toMap()).toList(),
      'logo': logo,
      'active': active,
      'type': type,
      'socials': socials?.map((e) => e.toMap()).toList(),
      'boardMembers': boardMembers?.map((e) => e.toMap()).toList(),
      'products': products?.map((e) => e.toMap()).toList(),
      'translations': translations?.map((e) => e.toMap()).toList(),
      'hero': hero,
      'campus': campus?.toMap(),
      'jobs': jobs?.map((e) => e.toMap()).toList(),
      'events': events?.map((e) => e.toMap()).toList(),
      'news': news?.map((e) => e.toMap()).toList()
    };
  }
}
