// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

enum DocumentsCategory {
  NATIONAL_STATUTES("national-statutes"),
  CAMPUS_BYLAWS("campus-bylaws"),
  CODE_OF_CONDUCT("code-of-conduct"),
  BUSINESS_REGULATIONS("business-regulations"),
  COMMUNICATION_GUIDELINES("communication-guidelines");

  const DocumentsCategory(this.value);
  final String value;

  static DocumentsCategory? fromValue(String? value) {
    if (value == null) return null;
    return DocumentsCategory.values.firstWhere((element) => element.value == value);
  }
}

enum DocumentsScope {
  NATIONAL("national"),
  CAMPUS("campus");

  const DocumentsScope(this.value);
  final String value;

  static DocumentsScope? fromValue(String? value) {
    if (value == null) return null;
    return DocumentsScope.values.firstWhere((element) => element.value == value);
  }
}

enum DocumentsStatus {
  DRAFT("draft"),
  PUBLISHED("published");

  const DocumentsStatus(this.value);
  final String value;

  static DocumentsStatus? fromValue(String? value) {
    if (value == null) return null;
    return DocumentsStatus.values.firstWhere((element) => element.value == value);
  }
}

class Documents {
  String title;
  DocumentsCategory category;
  DocumentsScope scope;
  String sharepoint_item_id;
  String sharepoint_drive_id;
  String sharepoint_web_url;
  String? description;
  String? campus_id;
  String? version;
  int? version_number;
  int? file_size;
  DocumentsStatus? status;
  int? sort_order;
  String? updated_by;

  Documents({
    required this.title,
    required this.category,
    required this.scope,
    required this.sharepoint_item_id,
    required this.sharepoint_drive_id,
    required this.sharepoint_web_url,
    this.description,
    this.campus_id,
    this.version,
    this.version_number,
    this.file_size,
    this.status,
    this.sort_order,
    this.updated_by
  });

  factory Documents.fromMap(Map<String, dynamic> map) {
    return Documents(
      title: map['title'].toString(),
      category: DocumentsCategory.values.firstWhere((e) => e.value == map['category']),
      scope: DocumentsScope.values.firstWhere((e) => e.value == map['scope']),
      sharepoint_item_id: map['sharepoint_item_id'].toString(),
      sharepoint_drive_id: map['sharepoint_drive_id'].toString(),
      sharepoint_web_url: map['sharepoint_web_url'].toString(),
      description: map['description']?.toString(),
      campus_id: map['campus_id']?.toString(),
      version: map['version']?.toString(),
      version_number: map['version_number'],
      file_size: map['file_size'],
      status: DocumentsStatus.fromValue(map['status']),
      sort_order: map['sort_order'],
      updated_by: map['updated_by']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'title': title,
      'category': category.value,
      'scope': scope.value,
      'sharepoint_item_id': sharepoint_item_id,
      'sharepoint_drive_id': sharepoint_drive_id,
      'sharepoint_web_url': sharepoint_web_url,
      'description': description,
      'campus_id': campus_id,
      'version': version,
      'version_number': version_number,
      'file_size': file_size,
      'status': status?.value,
      'sort_order': sort_order,
      'updated_by': updated_by
    };
  }
}
