// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'campus.dart';
import 'content_translations.dart';
import 'departments.dart';

enum EventsStatus {
  DRAFT("draft"),
  PUBLISHED("published"),
  CANCELLED("cancelled");

  const EventsStatus(this.value);
  final String value;

  static EventsStatus? fromValue(String? value) {
    if (value == null) return null;
    return EventsStatus.values.firstWhere((element) => element.value == value);
  }
}

enum EventsCollectionPricing {
  BUNDLE("bundle"),
  INDIVIDUAL("individual");

  const EventsCollectionPricing(this.value);
  final String value;

  static EventsCollectionPricing? fromValue(String? value) {
    if (value == null) return null;
    return EventsCollectionPricing.values.firstWhere((element) => element.value == value);
  }
}

class Events {
  EventsStatus status;
  String campus_id;
  String? slug;
  String? metadata;
  Campus? campus;
  List<ContentTranslations>? translation_refs;
  String? start_date;
  String? end_date;
  String? image;
  String? ticket_url;
  double? price;
  bool? member_only;
  String? collection_id;
  bool? is_collection;
  EventsCollectionPricing? collection_pricing;
  String? location;
  String? department_id;
  Departments? department;

  Events({
    required this.status,
    required this.campus_id,
    this.slug,
    this.metadata,
    this.campus,
    this.translation_refs,
    this.start_date,
    this.end_date,
    this.image,
    this.ticket_url,
    this.price,
    this.member_only,
    this.collection_id,
    this.is_collection,
    this.collection_pricing,
    this.location,
    this.department_id,
    this.department
  });

  factory Events.fromMap(Map<String, dynamic> map) {
    return Events(
      status: EventsStatus.values.firstWhere((e) => e.value == map['status']),
      campus_id: map['campus_id'].toString(),
      slug: map['slug']?.toString(),
      metadata: map['metadata']?.toString(),
      campus: map['campus'] != null ? Campus.fromMap(map['campus']) : null,
      translation_refs: (map['translation_refs'] as List<dynamic>?)?.map((e) => ContentTranslations.fromMap(e)).toList(),
      start_date: map['start_date']?.toString(),
      end_date: map['end_date']?.toString(),
      image: map['image']?.toString(),
      ticket_url: map['ticket_url']?.toString(),
      price: map['price'],
      member_only: map['member_only'],
      collection_id: map['collection_id']?.toString(),
      is_collection: map['is_collection'],
      collection_pricing: EventsCollectionPricing.fromValue(map['collection_pricing']),
      location: map['location']?.toString(),
      department_id: map['department_id']?.toString(),
      department: map['department'] != null ? Departments.fromMap(map['department']) : null
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'status': status.value,
      'campus_id': campus_id,
      'slug': slug,
      'metadata': metadata,
      'campus': campus?.toMap(),
      'translation_refs': translation_refs?.map((e) => e.toMap()).toList(),
      'start_date': start_date,
      'end_date': end_date,
      'image': image,
      'ticket_url': ticket_url,
      'price': price,
      'member_only': member_only,
      'collection_id': collection_id,
      'is_collection': is_collection,
      'collection_pricing': collection_pricing?.value,
      'location': location,
      'department_id': department_id,
      'department': department?.toMap()
    };
  }
}
