// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class ExpenseAttachments {
  String type;
  String? date;
  String? url;
  double? amount;
  String? description;

  ExpenseAttachments({
    required this.type,
    this.date,
    this.url,
    this.amount,
    this.description
  });

  factory ExpenseAttachments.fromMap(Map<String, dynamic> map) {
    return ExpenseAttachments(
      type: map['type'].toString(),
      date: map['date']?.toString(),
      url: map['url']?.toString(),
      amount: map['amount'],
      description: map['description']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'type': type,
      'date': date,
      'url': url,
      'amount': amount,
      'description': description
    };
  }
}
