// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'users.dart';
import 'expense_attachments.dart';
import 'departments.dart';
import 'campus.dart';

enum ExpensesStatus {
  DRAFT("draft"),
  PENDING("pending"),
  SUCCESS("success"),
  SUBMITTED("submitted"),
  REJECTED("rejected");

  const ExpensesStatus(this.value);
  final String value;

  static ExpensesStatus? fromValue(String? value) {
    if (value == null) return null;
    return ExpensesStatus.values.firstWhere((element) => element.value == value);
  }
}

class Expenses {
  String campus;
  String department;
  String bank_account;
  double total;
  String userId;
  Users? user;
  String? description;
  List<ExpenseAttachments>? expenseAttachments;
  double? prepayment_amount;
  ExpensesStatus? status;
  int? invoice_id;
  String? eventName;
  Departments? departmentRel;
  Campus? campusRel;

  Expenses({
    required this.campus,
    required this.department,
    required this.bank_account,
    required this.total,
    required this.userId,
    this.user,
    this.description,
    this.expenseAttachments,
    this.prepayment_amount,
    this.status,
    this.invoice_id,
    this.eventName,
    this.departmentRel,
    this.campusRel
  });

  factory Expenses.fromMap(Map<String, dynamic> map) {
    return Expenses(
      campus: map['campus'].toString(),
      department: map['department'].toString(),
      bank_account: map['bank_account'].toString(),
      total: map['total'],
      userId: map['userId'].toString(),
      user: map['user'] != null ? Users.fromMap(map['user']) : null,
      description: map['description']?.toString(),
      expenseAttachments: (map['expenseAttachments'] as List<dynamic>?)?.map((e) => ExpenseAttachments.fromMap(e)).toList(),
      prepayment_amount: map['prepayment_amount'],
      status: ExpensesStatus.fromValue(map['status']),
      invoice_id: map['invoice_id'],
      eventName: map['eventName']?.toString(),
      departmentRel: map['departmentRel'] != null ? Departments.fromMap(map['departmentRel']) : null,
      campusRel: map['campusRel'] != null ? Campus.fromMap(map['campusRel']) : null
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'campus': campus,
      'department': department,
      'bank_account': bank_account,
      'total': total,
      'userId': userId,
      'user': user?.toMap(),
      'description': description,
      'expenseAttachments': expenseAttachments?.map((e) => e.toMap()).toList(),
      'prepayment_amount': prepayment_amount,
      'status': status?.value,
      'invoice_id': invoice_id,
      'eventName': eventName,
      'departmentRel': departmentRel?.toMap(),
      'campusRel': campusRel?.toMap()
    };
  }
}
