// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class FeatureFlags {
  String key;
  bool enabled;
  String title;
  String? description;

  FeatureFlags({
    required this.key,
    required this.enabled,
    required this.title,
    this.description
  });

  factory FeatureFlags.fromMap(Map<String, dynamic> map) {
    return FeatureFlags(
      key: map['key'].toString(),
      enabled: map['enabled'],
      title: map['title'].toString(),
      description: map['description']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'key': key,
      'enabled': enabled,
      'title': title,
      'description': description
    };
  }
}
