// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class FollowedUnits {
  String user_id;
  List<String>? department_ids;

  FollowedUnits({
    required this.user_id,
    this.department_ids
  });

  factory FollowedUnits.fromMap(Map<String, dynamic> map) {
    return FollowedUnits(
      user_id: map['user_id'].toString(),
      department_ids: List<String>.from(map['department_ids'] ?? [])
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'user_id': user_id,
      'department_ids': department_ids
    };
  }
}
