// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class FundingPrograms {
  String slug;
  String? status;
  String? hero_image_url;
  String? application_url;
  String? document_url;
  String? contact_name;
  String? contact_email;
  String? contact_phone;
  String? metadata;

  FundingPrograms({
    required this.slug,
    this.status,
    this.hero_image_url,
    this.application_url,
    this.document_url,
    this.contact_name,
    this.contact_email,
    this.contact_phone,
    this.metadata
  });

  factory FundingPrograms.fromMap(Map<String, dynamic> map) {
    return FundingPrograms(
      slug: map['slug'].toString(),
      status: map['status']?.toString(),
      hero_image_url: map['hero_image_url']?.toString(),
      application_url: map['application_url']?.toString(),
      document_url: map['document_url']?.toString(),
      contact_name: map['contact_name']?.toString(),
      contact_email: map['contact_email']?.toString(),
      contact_phone: map['contact_phone']?.toString(),
      metadata: map['metadata']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'slug': slug,
      'status': status,
      'hero_image_url': hero_image_url,
      'application_url': application_url,
      'document_url': document_url,
      'contact_name': contact_name,
      'contact_email': contact_email,
      'contact_phone': contact_phone,
      'metadata': metadata
    };
  }
}
