// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

enum JobApplicationsStatus {
  SUBMITTED("submitted"),
  REVIEWED("reviewed"),
  INTERVIEW("interview"),
  ACCEPTED("accepted"),
  REJECTED("rejected");

  const JobApplicationsStatus(this.value);
  final String value;

  static JobApplicationsStatus? fromValue(String? value) {
    if (value == null) return null;
    return JobApplicationsStatus.values.firstWhere((element) => element.value == value);
  }
}

class JobApplications {
  String job_id;
  String applicant_name;
  String applicant_email;
  JobApplicationsStatus status;
  bool gdpr_consent;
  String consent_date;
  String data_processing_purpose;
  String data_retention_until;
  String? applicant_phone;
  String? cover_letter;
  String? resume_file_id;

  JobApplications({
    required this.job_id,
    required this.applicant_name,
    required this.applicant_email,
    required this.status,
    required this.gdpr_consent,
    required this.consent_date,
    required this.data_processing_purpose,
    required this.data_retention_until,
    this.applicant_phone,
    this.cover_letter,
    this.resume_file_id
  });

  factory JobApplications.fromMap(Map<String, dynamic> map) {
    return JobApplications(
      job_id: map['job_id'].toString(),
      applicant_name: map['applicant_name'].toString(),
      applicant_email: map['applicant_email'].toString(),
      status: JobApplicationsStatus.values.firstWhere((e) => e.value == map['status']),
      gdpr_consent: map['gdpr_consent'],
      consent_date: map['consent_date'].toString(),
      data_processing_purpose: map['data_processing_purpose'].toString(),
      data_retention_until: map['data_retention_until'].toString(),
      applicant_phone: map['applicant_phone']?.toString(),
      cover_letter: map['cover_letter']?.toString(),
      resume_file_id: map['resume_file_id']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'job_id': job_id,
      'applicant_name': applicant_name,
      'applicant_email': applicant_email,
      'status': status.value,
      'gdpr_consent': gdpr_consent,
      'consent_date': consent_date,
      'data_processing_purpose': data_processing_purpose,
      'data_retention_until': data_retention_until,
      'applicant_phone': applicant_phone,
      'cover_letter': cover_letter,
      'resume_file_id': resume_file_id
    };
  }
}
