// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'content_translations.dart';
import 'campus.dart';
import 'departments.dart';

enum JobsStatus {
  DRAFT("draft"),
  PUBLISHED("published"),
  CLOSED("closed");

  const JobsStatus(this.value);
  final String value;

  static JobsStatus? fromValue(String? value) {
    if (value == null) return null;
    return JobsStatus.values.firstWhere((element) => element.value == value);
  }
}

class Jobs {
  String slug;
  JobsStatus status;
  String campus_id;
  List<ContentTranslations>? translation_refs;
  String? department_id;
  String? metadata;
  Campus? campus;
  List<ContentTranslations>? translations;
  Departments? department;

  Jobs({
    required this.slug,
    required this.status,
    required this.campus_id,
    this.translation_refs,
    this.department_id,
    this.metadata,
    this.campus,
    this.translations,
    this.department
  });

  factory Jobs.fromMap(Map<String, dynamic> map) {
    return Jobs(
      slug: map['slug'].toString(),
      status: JobsStatus.values.firstWhere((e) => e.value == map['status']),
      campus_id: map['campus_id'].toString(),
      translation_refs: (map['translation_refs'] as List<dynamic>?)?.map((e) => ContentTranslations.fromMap(e)).toList(),
      department_id: map['department_id']?.toString(),
      metadata: map['metadata']?.toString(),
      campus: map['campus'] != null ? Campus.fromMap(map['campus']) : null,
      translations: (map['translations'] as List<dynamic>?)?.map((e) => ContentTranslations.fromMap(e)).toList(),
      department: map['department'] != null ? Departments.fromMap(map['department']) : null
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'slug': slug,
      'status': status.value,
      'campus_id': campus_id,
      'translation_refs': translation_refs?.map((e) => e.toMap()).toList(),
      'department_id': department_id,
      'metadata': metadata,
      'campus': campus?.toMap(),
      'translations': translations?.map((e) => e.toMap()).toList(),
      'department': department?.toMap()
    };
  }
}
