// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class LargeEvent {
  String slug;
  String name;
  String description;
  String startDate;
  String endDate;
  bool isActive;
  bool heroOverrideEnabled;
  int priority;
  String? primaryColorHex;
  String? secondaryColorHex;
  String? textColorHex;
  List<String>? gradientHex;
  String? logoUrl;
  String? backgroundImageUrl;
  String? campusConfigs;
  String? showcaseType;
  String? contentMetadata;
  String? externalUrl;
  String? ctaText;

  LargeEvent({
    required this.slug,
    required this.name,
    required this.description,
    required this.startDate,
    required this.endDate,
    required this.isActive,
    required this.heroOverrideEnabled,
    required this.priority,
    this.primaryColorHex,
    this.secondaryColorHex,
    this.textColorHex,
    this.gradientHex,
    this.logoUrl,
    this.backgroundImageUrl,
    this.campusConfigs,
    this.showcaseType,
    this.contentMetadata,
    this.externalUrl,
    this.ctaText
  });

  factory LargeEvent.fromMap(Map<String, dynamic> map) {
    return LargeEvent(
      slug: map['slug'].toString(),
      name: map['name'].toString(),
      description: map['description'].toString(),
      startDate: map['startDate'].toString(),
      endDate: map['endDate'].toString(),
      isActive: map['isActive'],
      heroOverrideEnabled: map['heroOverrideEnabled'],
      priority: map['priority'],
      primaryColorHex: map['primaryColorHex']?.toString(),
      secondaryColorHex: map['secondaryColorHex']?.toString(),
      textColorHex: map['textColorHex']?.toString(),
      gradientHex: List<String>.from(map['gradientHex'] ?? []),
      logoUrl: map['logoUrl']?.toString(),
      backgroundImageUrl: map['backgroundImageUrl']?.toString(),
      campusConfigs: map['campusConfigs']?.toString(),
      showcaseType: map['showcaseType']?.toString(),
      contentMetadata: map['contentMetadata']?.toString(),
      externalUrl: map['externalUrl']?.toString(),
      ctaText: map['ctaText']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'slug': slug,
      'name': name,
      'description': description,
      'startDate': startDate,
      'endDate': endDate,
      'isActive': isActive,
      'heroOverrideEnabled': heroOverrideEnabled,
      'priority': priority,
      'primaryColorHex': primaryColorHex,
      'secondaryColorHex': secondaryColorHex,
      'textColorHex': textColorHex,
      'gradientHex': gradientHex,
      'logoUrl': logoUrl,
      'backgroundImageUrl': backgroundImageUrl,
      'campusConfigs': campusConfigs,
      'showcaseType': showcaseType,
      'contentMetadata': contentMetadata,
      'externalUrl': externalUrl,
      'ctaText': ctaText
    };
  }
}
