// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'student_ids.dart';
import 'payments.dart';

class Memberships {
  String membership_id;
  String name;
  double price;
  bool status;
  String expiryDate;
  bool canPurchase;
  String startDate;
  List<StudentIds>? studentId;
  String? category;
  List<Payments>? payments;

  Memberships({
    required this.membership_id,
    required this.name,
    required this.price,
    required this.status,
    required this.expiryDate,
    required this.canPurchase,
    required this.startDate,
    this.studentId,
    this.category,
    this.payments
  });

  factory Memberships.fromMap(Map<String, dynamic> map) {
    return Memberships(
      membership_id: map['membership_id'].toString(),
      name: map['name'].toString(),
      price: map['price'],
      status: map['status'],
      expiryDate: map['expiryDate'].toString(),
      canPurchase: map['canPurchase'],
      startDate: map['startDate'].toString(),
      studentId: (map['studentId'] as List<dynamic>?)?.map((e) => StudentIds.fromMap(e)).toList(),
      category: map['category']?.toString(),
      payments: (map['payments'] as List<dynamic>?)?.map((e) => Payments.fromMap(e)).toList()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'membership_id': membership_id,
      'name': name,
      'price': price,
      'status': status,
      'expiryDate': expiryDate,
      'canPurchase': canPurchase,
      'startDate': startDate,
      'studentId': studentId?.map((e) => e.toMap()).toList(),
      'category': category,
      'payments': payments?.map((e) => e.toMap()).toList()
    };
  }
}
