// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'campus.dart';
import 'content_translations.dart';
import 'departments.dart';

enum NewsStatus {
  DRAFT("draft"),
  PUBLISHED("published");

  const NewsStatus(this.value);
  final String value;

  static NewsStatus? fromValue(String? value) {
    if (value == null) return null;
    return NewsStatus.values.firstWhere((element) => element.value == value);
  }
}

class News {
  NewsStatus status;
  String campus_id;
  String? slug;
  String? department_id;
  bool? sticky;
  Campus? campus;
  List<ContentTranslations>? translation_refs;
  String? url;
  String? image;
  Departments? department;
  List<String>? metadata;
  String? author;

  News({
    required this.status,
    required this.campus_id,
    this.slug,
    this.department_id,
    this.sticky,
    this.campus,
    this.translation_refs,
    this.url,
    this.image,
    this.department,
    this.metadata,
    this.author
  });

  factory News.fromMap(Map<String, dynamic> map) {
    return News(
      status: NewsStatus.values.firstWhere((e) => e.value == map['status']),
      campus_id: map['campus_id'].toString(),
      slug: map['slug']?.toString(),
      department_id: map['department_id']?.toString(),
      sticky: map['sticky'],
      campus: map['campus'] != null ? Campus.fromMap(map['campus']) : null,
      translation_refs: (map['translation_refs'] as List<dynamic>?)?.map((e) => ContentTranslations.fromMap(e)).toList(),
      url: map['url']?.toString(),
      image: map['image']?.toString(),
      department: map['department'] != null ? Departments.fromMap(map['department']) : null,
      metadata: List<String>.from(map['metadata'] ?? []),
      author: map['author']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'status': status.value,
      'campus_id': campus_id,
      'slug': slug,
      'department_id': department_id,
      'sticky': sticky,
      'campus': campus?.toMap(),
      'translation_refs': translation_refs?.map((e) => e.toMap()).toList(),
      'url': url,
      'image': image,
      'department': department?.toMap(),
      'metadata': metadata,
      'author': author
    };
  }
}
