// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

enum NotificationsStatus {
  READ("read"),
  UNREAD("unread");

  const NotificationsStatus(this.value);
  final String value;

  static NotificationsStatus? fromValue(String? value) {
    if (value == null) return null;
    return NotificationsStatus.values.firstWhere((element) => element.value == value);
  }
}

class Notifications {
  NotificationsStatus? status;

  Notifications({
    this.status
  });

  factory Notifications.fromMap(Map<String, dynamic> map) {
    return Notifications(
      status: NotificationsStatus.fromValue(map['status'])
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'status': status?.value
    };
  }
}
