// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

enum OrdersCurrency {
  NOK("NOK");

  const OrdersCurrency(this.value);
  final String value;

  static OrdersCurrency? fromValue(String? value) {
    if (value == null) return null;
    return OrdersCurrency.values.firstWhere((element) => element.value == value);
  }
}

enum OrdersStatus {
  PENDING("pending"),
  AUTHORIZED("authorized"),
  PAID("paid"),
  CANCELLED("cancelled"),
  FAILED("failed"),
  REFUNDED("refunded");

  const OrdersStatus(this.value);
  final String value;

  static OrdersStatus? fromValue(String? value) {
    if (value == null) return null;
    return OrdersStatus.values.firstWhere((element) => element.value == value);
  }
}

class Orders {
  double subtotal;
  double total;
  OrdersCurrency currency;
  OrdersStatus? status;
  String? userId;
  String? buyer_name;
  String? buyer_email;
  String? buyer_phone;
  double? discount_total;
  String? items_json;
  bool? membership_applied;
  double? member_discount_percent;
  String? campus_id;
  String? payment_provider;
  String? payment_session_id;
  String? payment_intent_id;
  String? receipt_link;
  String? payment_receipt_url;
  String? payment_link;

  Orders({
    required this.subtotal,
    required this.total,
    required this.currency,
    this.status,
    this.userId,
    this.buyer_name,
    this.buyer_email,
    this.buyer_phone,
    this.discount_total,
    this.items_json,
    this.membership_applied,
    this.member_discount_percent,
    this.campus_id,
    this.payment_provider,
    this.payment_session_id,
    this.payment_intent_id,
    this.receipt_link,
    this.payment_receipt_url,
    this.payment_link
  });

  factory Orders.fromMap(Map<String, dynamic> map) {
    return Orders(
      subtotal: map['subtotal'],
      total: map['total'],
      currency: OrdersCurrency.values.firstWhere((e) => e.value == map['currency']),
      status: OrdersStatus.fromValue(map['status']),
      userId: map['userId']?.toString(),
      buyer_name: map['buyer_name']?.toString(),
      buyer_email: map['buyer_email']?.toString(),
      buyer_phone: map['buyer_phone']?.toString(),
      discount_total: map['discount_total'],
      items_json: map['items_json']?.toString(),
      membership_applied: map['membership_applied'],
      member_discount_percent: map['member_discount_percent'],
      campus_id: map['campus_id']?.toString(),
      payment_provider: map['payment_provider']?.toString(),
      payment_session_id: map['payment_session_id']?.toString(),
      payment_intent_id: map['payment_intent_id']?.toString(),
      receipt_link: map['receipt_link']?.toString(),
      payment_receipt_url: map['payment_receipt_url']?.toString(),
      payment_link: map['payment_link']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'subtotal': subtotal,
      'total': total,
      'currency': currency.value,
      'status': status?.value,
      'userId': userId,
      'buyer_name': buyer_name,
      'buyer_email': buyer_email,
      'buyer_phone': buyer_phone,
      'discount_total': discount_total,
      'items_json': items_json,
      'membership_applied': membership_applied,
      'member_discount_percent': member_discount_percent,
      'campus_id': campus_id,
      'payment_provider': payment_provider,
      'payment_session_id': payment_session_id,
      'payment_intent_id': payment_intent_id,
      'receipt_link': receipt_link,
      'payment_receipt_url': payment_receipt_url,
      'payment_link': payment_link
    };
  }
}
