// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'pages.dart';

enum PageTranslationsLocale {
  NO("no"),
  EN("en");

  const PageTranslationsLocale(this.value);
  final String value;

  static PageTranslationsLocale? fromValue(String? value) {
    if (value == null) return null;
    return PageTranslationsLocale.values.firstWhere((element) => element.value == value);
  }
}

class PageTranslations {
  String page_id;
  String root;
  String content;
  String zones;
  Pages? page;
  PageTranslationsLocale? locale;
  String? puck_document;
  String? draft_document;
  bool? is_published;
  String? published_at;

  PageTranslations({
    required this.page_id,
    required this.root,
    required this.content,
    required this.zones,
    this.page,
    this.locale,
    this.puck_document,
    this.draft_document,
    this.is_published,
    this.published_at
  });

  factory PageTranslations.fromMap(Map<String, dynamic> map) {
    return PageTranslations(
      page_id: map['page_id'].toString(),
      root: map['root'].toString(),
      content: map['content'].toString(),
      zones: map['zones'].toString(),
      page: map['page'] != null ? Pages.fromMap(map['page']) : null,
      locale: PageTranslationsLocale.fromValue(map['locale']),
      puck_document: map['puck_document']?.toString(),
      draft_document: map['draft_document']?.toString(),
      is_published: map['is_published'],
      published_at: map['published_at']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'page_id': page_id,
      'root': root,
      'content': content,
      'zones': zones,
      'page': page?.toMap(),
      'locale': locale?.value,
      'puck_document': puck_document,
      'draft_document': draft_document,
      'is_published': is_published,
      'published_at': published_at
    };
  }
}
