// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

enum PageViewEventsLocale {
  EN("en"),
  NO("no");

  const PageViewEventsLocale(this.value);
  final String value;

  static PageViewEventsLocale? fromValue(String? value) {
    if (value == null) return null;
    return PageViewEventsLocale.values.firstWhere((element) => element.value == value);
  }
}

class PageViewEvents {
  String path;
  PageViewEventsLocale? locale;
  String? referrer;
  String? user_agent;
  String? visitor_ip;
  String? user_id;

  PageViewEvents({
    required this.path,
    this.locale,
    this.referrer,
    this.user_agent,
    this.visitor_ip,
    this.user_id
  });

  factory PageViewEvents.fromMap(Map<String, dynamic> map) {
    return PageViewEvents(
      path: map['path'].toString(),
      locale: PageViewEventsLocale.fromValue(map['locale']),
      referrer: map['referrer']?.toString(),
      user_agent: map['user_agent']?.toString(),
      visitor_ip: map['visitor_ip']?.toString(),
      user_id: map['user_id']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'path': path,
      'locale': locale?.value,
      'referrer': referrer,
      'user_agent': user_agent,
      'visitor_ip': visitor_ip,
      'user_id': user_id
    };
  }
}
