// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'campus.dart';
import 'page_translations.dart';

enum PagesStatus {
  DRAFT("draft"),
  PUBLISHED("published"),
  ARCHIVED("archived");

  const PagesStatus(this.value);
  final String value;

  static PagesStatus? fromValue(String? value) {
    if (value == null) return null;
    return PagesStatus.values.firstWhere((element) => element.value == value);
  }
}

enum PagesVisibility {
  PUBLIC("public"),
  AUTHENTICATED("authenticated");

  const PagesVisibility(this.value);
  final String value;

  static PagesVisibility? fromValue(String? value) {
    if (value == null) return null;
    return PagesVisibility.values.firstWhere((element) => element.value == value);
  }
}

class Pages {
  String? slug;
  String? campus_id;
  Campus? campus;
  PagesStatus? status;
  PagesVisibility? visibility;
  String? department_id;
  List<PageTranslations>? translation_refs;

  Pages({
    this.slug,
    this.campus_id,
    this.campus,
    this.status,
    this.visibility,
    this.department_id,
    this.translation_refs
  });

  factory Pages.fromMap(Map<String, dynamic> map) {
    return Pages(
      slug: map['slug']?.toString(),
      campus_id: map['campus_id']?.toString(),
      campus: map['campus'] != null ? Campus.fromMap(map['campus']) : null,
      status: PagesStatus.fromValue(map['status']),
      visibility: PagesVisibility.fromValue(map['visibility']),
      department_id: map['department_id']?.toString(),
      translation_refs: (map['translation_refs'] as List<dynamic>?)?.map((e) => PageTranslations.fromMap(e)).toList()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'slug': slug,
      'campus_id': campus_id,
      'campus': campus?.toMap(),
      'status': status?.value,
      'visibility': visibility?.value,
      'department_id': department_id,
      'translation_refs': translation_refs?.map((e) => e.toMap()).toList()
    };
  }
}
