// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'campus.dart';

enum PartnersLevel {
  NATIONAL("national"),
  CAMPUS("campus");

  const PartnersLevel(this.value);
  final String value;

  static PartnersLevel? fromValue(String? value) {
    if (value == null) return null;
    return PartnersLevel.values.firstWhere((element) => element.value == value);
  }
}

class Partners {
  String name;
  PartnersLevel level;
  String image_url;
  String campus_id;
  String? url;
  Campus? campus;

  Partners({
    required this.name,
    required this.level,
    required this.image_url,
    required this.campus_id,
    this.url,
    this.campus
  });

  factory Partners.fromMap(Map<String, dynamic> map) {
    return Partners(
      name: map['name'].toString(),
      level: PartnersLevel.values.firstWhere((e) => e.value == map['level']),
      image_url: map['image_url'].toString(),
      campus_id: map['campus_id'].toString(),
      url: map['url']?.toString(),
      campus: map['campus'] != null ? Campus.fromMap(map['campus']) : null
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'level': level.value,
      'image_url': image_url,
      'campus_id': campus_id,
      'url': url,
      'campus': campus?.toMap()
    };
  }
}
