// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'memberships.dart';
import 'users.dart';

class Payments {
  String reference;
  double amount;
  String? description;
  String? membership_id;
  Memberships? membership;
  String? status;
  double? paid_amount;
  Users? user;
  String? payment_method;
  String? user_id;

  Payments({
    required this.reference,
    required this.amount,
    this.description,
    this.membership_id,
    this.membership,
    this.status,
    this.paid_amount,
    this.user,
    this.payment_method,
    this.user_id
  });

  factory Payments.fromMap(Map<String, dynamic> map) {
    return Payments(
      reference: map['reference'].toString(),
      amount: map['amount'],
      description: map['description']?.toString(),
      membership_id: map['membership_id']?.toString(),
      membership: map['membership'] != null ? Memberships.fromMap(map['membership']) : null,
      status: map['status']?.toString(),
      paid_amount: map['paid_amount'],
      user: map['user'] != null ? Users.fromMap(map['user']) : null,
      payment_method: map['payment_method']?.toString(),
      user_id: map['user_id']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'reference': reference,
      'amount': amount,
      'description': description,
      'membership_id': membership_id,
      'membership': membership?.toMap(),
      'status': status,
      'paid_amount': paid_amount,
      'user': user?.toMap(),
      'payment_method': payment_method,
      'user_id': user_id
    };
  }
}
