// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'product_favorites.dart';

enum ProductsCondition {
  NEW("new"),
  LIKE_NEW("like_new"),
  GOOD("good"),
  FAIR("fair"),
  POOR("poor");

  const ProductsCondition(this.value);
  final String value;

  static ProductsCondition? fromValue(String? value) {
    if (value == null) return null;
    return ProductsCondition.values.firstWhere((element) => element.value == value);
  }
}

enum ProductsStatus {
  AVAILABLE("available"),
  SOLD("sold"),
  RESERVED("reserved"),
  INACTIVE("inactive");

  const ProductsStatus(this.value);
  final String value;

  static ProductsStatus? fromValue(String? value) {
    if (value == null) return null;
    return ProductsStatus.values.firstWhere((element) => element.value == value);
  }
}

enum ProductsContactMethod {
  MESSAGE("message"),
  PHONE("phone"),
  EMAIL("email");

  const ProductsContactMethod(this.value);
  final String value;

  static ProductsContactMethod? fromValue(String? value) {
    if (value == null) return null;
    return ProductsContactMethod.values.firstWhere((element) => element.value == value);
  }
}

class Products {
  String name;
  String description;
  double price;
  String currency;
  String seller_id;
  String seller_name;
  String campus_id;
  String category;
  ProductsCondition condition;
  ProductsStatus status;
  String? seller_avatar;
  List<String>? images;
  bool? is_negotiable;
  ProductsContactMethod? contact_method;
  String? contact_info;
  int? view_count;
  int? favorite_count;
  List<String>? image_file_ids;
  List<ProductFavorites>? favorites;

  Products({
    required this.name,
    required this.description,
    required this.price,
    required this.currency,
    required this.seller_id,
    required this.seller_name,
    required this.campus_id,
    required this.category,
    required this.condition,
    required this.status,
    this.seller_avatar,
    this.images,
    this.is_negotiable,
    this.contact_method,
    this.contact_info,
    this.view_count,
    this.favorite_count,
    this.image_file_ids,
    this.favorites
  });

  factory Products.fromMap(Map<String, dynamic> map) {
    return Products(
      name: map['name'].toString(),
      description: map['description'].toString(),
      price: map['price'],
      currency: map['currency'].toString(),
      seller_id: map['seller_id'].toString(),
      seller_name: map['seller_name'].toString(),
      campus_id: map['campus_id'].toString(),
      category: map['category'].toString(),
      condition: ProductsCondition.values.firstWhere((e) => e.value == map['condition']),
      status: ProductsStatus.values.firstWhere((e) => e.value == map['status']),
      seller_avatar: map['seller_avatar']?.toString(),
      images: List<String>.from(map['images'] ?? []),
      is_negotiable: map['is_negotiable'],
      contact_method: ProductsContactMethod.fromValue(map['contact_method']),
      contact_info: map['contact_info']?.toString(),
      view_count: map['view_count'],
      favorite_count: map['favorite_count'],
      image_file_ids: List<String>.from(map['image_file_ids'] ?? []),
      favorites: (map['favorites'] as List<dynamic>?)?.map((e) => ProductFavorites.fromMap(e)).toList()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'description': description,
      'price': price,
      'currency': currency,
      'seller_id': seller_id,
      'seller_name': seller_name,
      'campus_id': campus_id,
      'category': category,
      'condition': condition.value,
      'status': status.value,
      'seller_avatar': seller_avatar,
      'images': images,
      'is_negotiable': is_negotiable,
      'contact_method': contact_method?.value,
      'contact_info': contact_info,
      'view_count': view_count,
      'favorite_count': favorite_count,
      'image_file_ids': image_file_ids,
      'favorites': favorites?.map((e) => e.toMap()).toList()
    };
  }
}
