// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'products.dart';

class ProductFavorites {
  String user_id;
  Products? product;

  ProductFavorites({
    required this.user_id,
    this.product
  });

  factory ProductFavorites.fromMap(Map<String, dynamic> map) {
    return ProductFavorites(
      user_id: map['user_id'].toString(),
      product: map['product'] != null ? Products.fromMap(map['product']) : null
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'user_id': user_id,
      'product': product?.toMap()
    };
  }
}
