// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class PublicProfiles {
  String user_id;
  String name;
  String? email;
  String? phone;
  String? campus_id;
  String? avatar;
  bool? email_visible;
  bool? phone_visible;

  PublicProfiles({
    required this.user_id,
    required this.name,
    this.email,
    this.phone,
    this.campus_id,
    this.avatar,
    this.email_visible,
    this.phone_visible
  });

  factory PublicProfiles.fromMap(Map<String, dynamic> map) {
    return PublicProfiles(
      user_id: map['user_id'].toString(),
      name: map['name'].toString(),
      email: map['email']?.toString(),
      phone: map['phone']?.toString(),
      campus_id: map['campus_id']?.toString(),
      avatar: map['avatar']?.toString(),
      email_visible: map['email_visible'],
      phone_visible: map['phone_visible']
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'user_id': user_id,
      'name': name,
      'email': email,
      'phone': phone,
      'campus_id': campus_id,
      'avatar': avatar,
      'email_visible': email_visible,
      'phone_visible': phone_visible
    };
  }
}
