// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'campus.dart';
import 'users.dart';

class SavedJobs {
  int jobId;
  String title;
  List<Campus>? campus;
  List<Users>? user;

  SavedJobs({
    required this.jobId,
    required this.title,
    this.campus,
    this.user
  });

  factory SavedJobs.fromMap(Map<String, dynamic> map) {
    return SavedJobs(
      jobId: map['jobId'],
      title: map['title'].toString(),
      campus: (map['campus'] as List<dynamic>?)?.map((e) => Campus.fromMap(e)).toList(),
      user: (map['user'] as List<dynamic>?)?.map((e) => Users.fromMap(e)).toList()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'jobId': jobId,
      'title': title,
      'campus': campus?.map((e) => e.toMap()).toList(),
      'user': user?.map((e) => e.toMap()).toList()
    };
  }
}
