// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class ShopSettings {
  String? general;

  ShopSettings({
    this.general
  });

  factory ShopSettings.fromMap(Map<String, dynamic> map) {
    return ShopSettings(
      general: map['general']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'general': general
    };
  }
}
