// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class SitePages {
  String slug;
  String? status;

  SitePages({
    required this.slug,
    this.status
  });

  factory SitePages.fromMap(Map<String, dynamic> map) {
    return SitePages(
      slug: map['slug'].toString(),
      status: map['status']?.toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'slug': slug,
      'status': status
    };
  }
}
