// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'users.dart';
import 'memberships.dart';

class StudentIds {
  String student_id;
  Users? user;
  String? expiry_date;
  bool? isMember;
  List<Memberships>? memberships;
  List<String>? membership_ids;

  StudentIds({
    required this.student_id,
    this.user,
    this.expiry_date,
    this.isMember,
    this.memberships,
    this.membership_ids
  });

  factory StudentIds.fromMap(Map<String, dynamic> map) {
    return StudentIds(
      student_id: map['student_id'].toString(),
      user: map['user'] != null ? Users.fromMap(map['user']) : null,
      expiry_date: map['expiry_date']?.toString(),
      isMember: map['isMember'],
      memberships: (map['memberships'] as List<dynamic>?)?.map((e) => Memberships.fromMap(e)).toList(),
      membership_ids: List<String>.from(map['membership_ids'] ?? [])
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'student_id': student_id,
      'user': user?.toMap(),
      'expiry_date': expiry_date,
      'isMember': isMember,
      'memberships': memberships?.map((e) => e.toMap()).toList(),
      'membership_ids': membership_ids
    };
  }
}
