// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class Subscriptions {
  String user_id;
  String topic;
  bool subscribed;
  String subscriber_id;

  Subscriptions({
    required this.user_id,
    required this.topic,
    required this.subscribed,
    required this.subscriber_id
  });

  factory Subscriptions.fromMap(Map<String, dynamic> map) {
    return Subscriptions(
      user_id: map['user_id'].toString(),
      topic: map['topic'].toString(),
      subscribed: map['subscribed'],
      subscriber_id: map['subscriber_id'].toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'user_id': user_id,
      'topic': topic,
      'subscribed': subscribed,
      'subscriber_id': subscriber_id
    };
  }
}
