// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class TaxCodes {
  String code;
  String name;
  double rate;
  bool? active;

  TaxCodes({
    required this.code,
    required this.name,
    required this.rate,
    this.active
  });

  factory TaxCodes.fromMap(Map<String, dynamic> map) {
    return TaxCodes(
      code: map['code'].toString(),
      name: map['name'].toString(),
      rate: map['rate'],
      active: map['active']
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'code': code,
      'name': name,
      'rate': rate,
      'active': active
    };
  }
}
