// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class Teams {
  String name;
  List<String> members;
  int? total;

  Teams({
    required this.name,
    required this.members,
    this.total
  });

  factory Teams.fromMap(Map<String, dynamic> map) {
    return Teams(
      name: map['name'].toString(),
      members: List<String>.from(map['members'] ?? []),
      total: map['total']
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'members': members,
      'total': total
    };
  }
}
