// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class TypingIndicators {
  String chat_id;
  String user_id;
  String user_name;
  bool is_typing;
  String expires_at;

  TypingIndicators({
    required this.chat_id,
    required this.user_id,
    required this.user_name,
    required this.is_typing,
    required this.expires_at
  });

  factory TypingIndicators.fromMap(Map<String, dynamic> map) {
    return TypingIndicators(
      chat_id: map['chat_id'].toString(),
      user_id: map['user_id'].toString(),
      user_name: map['user_name'].toString(),
      is_typing: map['is_typing'],
      expires_at: map['expires_at'].toString()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'chat_id': chat_id,
      'user_id': user_id,
      'user_name': user_name,
      'is_typing': is_typing,
      'expires_at': expires_at
    };
  }
}
