// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'departments.dart';
import 'expenses.dart';
import 'student_ids.dart';
import 'campus.dart';
import 'payments.dart';
import 'saved_jobs.dart';

class Users {
  String? phone;
  String? address;
  String? city;
  String? zip;
  String? bank_account;
  String? name;
  String? email;
  List<Departments>? departments;
  List<Expenses>? expenses;
  String? campus_id;
  List<String>? department_ids;
  List<String>? membership_ids;
  String? student_id;
  StudentIds? studentId;
  String? avatar;
  List<String>? roles;
  bool? isActive;
  String? swift;
  bool? is_public;
  String? bio;
  Campus? campus;
  List<Payments>? payments;
  List<SavedJobs>? savedJobs;

  Users({
    this.phone,
    this.address,
    this.city,
    this.zip,
    this.bank_account,
    this.name,
    this.email,
    this.departments,
    this.expenses,
    this.campus_id,
    this.department_ids,
    this.membership_ids,
    this.student_id,
    this.studentId,
    this.avatar,
    this.roles,
    this.isActive,
    this.swift,
    this.is_public,
    this.bio,
    this.campus,
    this.payments,
    this.savedJobs
  });

  factory Users.fromMap(Map<String, dynamic> map) {
    return Users(
      phone: map['phone']?.toString(),
      address: map['address']?.toString(),
      city: map['city']?.toString(),
      zip: map['zip']?.toString(),
      bank_account: map['bank_account']?.toString(),
      name: map['name']?.toString(),
      email: map['email']?.toString(),
      departments: (map['departments'] as List<dynamic>?)?.map((e) => Departments.fromMap(e)).toList(),
      expenses: (map['expenses'] as List<dynamic>?)?.map((e) => Expenses.fromMap(e)).toList(),
      campus_id: map['campus_id']?.toString(),
      department_ids: List<String>.from(map['department_ids'] ?? []),
      membership_ids: List<String>.from(map['membership_ids'] ?? []),
      student_id: map['student_id']?.toString(),
      studentId: map['studentId'] != null ? StudentIds.fromMap(map['studentId']) : null,
      avatar: map['avatar']?.toString(),
      roles: List<String>.from(map['roles'] ?? []),
      isActive: map['isActive'],
      swift: map['swift']?.toString(),
      is_public: map['is_public'],
      bio: map['bio']?.toString(),
      campus: map['campus'] != null ? Campus.fromMap(map['campus']) : null,
      payments: (map['payments'] as List<dynamic>?)?.map((e) => Payments.fromMap(e)).toList(),
      savedJobs: (map['savedJobs'] as List<dynamic>?)?.map((e) => SavedJobs.fromMap(e)).toList()
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'phone': phone,
      'address': address,
      'city': city,
      'zip': zip,
      'bank_account': bank_account,
      'name': name,
      'email': email,
      'departments': departments?.map((e) => e.toMap()).toList(),
      'expenses': expenses?.map((e) => e.toMap()).toList(),
      'campus_id': campus_id,
      'department_ids': department_ids,
      'membership_ids': membership_ids,
      'student_id': student_id,
      'studentId': studentId?.toMap(),
      'avatar': avatar,
      'roles': roles,
      'isActive': isActive,
      'swift': swift,
      'is_public': is_public,
      'bio': bio,
      'campus': campus?.toMap(),
      'payments': payments?.map((e) => e.toMap()).toList(),
      'savedJobs': savedJobs?.map((e) => e.toMap()).toList()
    };
  }
}
