// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.

class VarslingSettings {
  String campus_id;
  String role_name;
  String email;
  int? sort_order;
  bool? is_active;

  VarslingSettings({
    required this.campus_id,
    required this.role_name,
    required this.email,
    this.sort_order,
    this.is_active
  });

  factory VarslingSettings.fromMap(Map<String, dynamic> map) {
    return VarslingSettings(
      campus_id: map['campus_id'].toString(),
      role_name: map['role_name'].toString(),
      email: map['email'].toString(),
      sort_order: map['sort_order'],
      is_active: map['is_active']
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'campus_id': campus_id,
      'role_name': role_name,
      'email': email,
      'sort_order': sort_order,
      'is_active': is_active
    };
  }
}
