// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language dart ./lib/types`.
import 'departments.dart';
import 'campus.dart';
import 'content_translations.dart';

enum WebshopProductsStatus {
  DRAFT("draft"),
  PENDING_APPROVAL("pending_approval"),
  PUBLISHED("published"),
  ARCHIVED("archived");

  const WebshopProductsStatus(this.value);
  final String value;

  static WebshopProductsStatus? fromValue(String? value) {
    if (value == null) return null;
    return WebshopProductsStatus.values.firstWhere((element) => element.value == value);
  }
}

class WebshopProducts {
  String slug;
  WebshopProductsStatus status;
  String campus_id;
  double regular_price;
  Departments? department;
  String? metadata;
  Campus? campus;
  List<ContentTranslations>? translation_refs;
  String? departmentId;
  double? member_price;
  bool? member_only;
  String? category;
  String? image;
  int? stock;

  WebshopProducts({
    required this.slug,
    required this.status,
    required this.campus_id,
    required this.regular_price,
    this.department,
    this.metadata,
    this.campus,
    this.translation_refs,
    this.departmentId,
    this.member_price,
    this.member_only,
    this.category,
    this.image,
    this.stock
  });

  factory WebshopProducts.fromMap(Map<String, dynamic> map) {
    return WebshopProducts(
      slug: map['slug'].toString(),
      status: WebshopProductsStatus.values.firstWhere((e) => e.value == map['status']),
      campus_id: map['campus_id'].toString(),
      regular_price: map['regular_price'],
      department: map['department'] != null ? Departments.fromMap(map['department']) : null,
      metadata: map['metadata']?.toString(),
      campus: map['campus'] != null ? Campus.fromMap(map['campus']) : null,
      translation_refs: (map['translation_refs'] as List<dynamic>?)?.map((e) => ContentTranslations.fromMap(e)).toList(),
      departmentId: map['departmentId']?.toString(),
      member_price: map['member_price'],
      member_only: map['member_only'],
      category: map['category']?.toString(),
      image: map['image']?.toString(),
      stock: map['stock']
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'slug': slug,
      'status': status.value,
      'campus_id': campus_id,
      'regular_price': regular_price,
      'department': department?.toMap(),
      'metadata': metadata,
      'campus': campus?.toMap(),
      'translation_refs': translation_refs?.map((e) => e.toMap()).toList(),
      'departmentId': departmentId,
      'member_price': member_price,
      'member_only': member_only,
      'category': category,
      'image': image,
      'stock': stock
    };
  }
}
